# Signature Scoring Explorer (classic Shiny) -- composition of reusable
# component modules over one signature dataset (expression + metadata + gene-set
# signatures). Scores MSigDB Hallmark sets across samples and compares them
# between groups.
#
# App (L3) layer: page layout + wiring only. Compute lives in the logic layer
# (R/_shared, Shiny-free); UI in the component modules (R/_modules).
#
# Vendored copy. This directory is self-contained: it runs and deploys on its
# own, with its own modules and its own data. Upstream is
# posit-dev/lifescience-shiny-gallery, where R/_shared and R/_modules are
# generated by scripts/sync-shared.R and git-ignored; here they are checked in.
# Change them upstream and re-copy rather than editing them in place.

# Dev convenience: load a local, git-ignored .Renviron (e.g. BYOK API keys) from
# the app dir or any parent up to the repo root, so Sys.getenv() sees them when
# the app is launched from its own working directory. A no-op when absent -- the
# deployed bundle has none; on the gallery, set env vars in the deploy config.
local({
  dir <- normalizePath(".", mustWork = FALSE)
  repeat {
    f <- file.path(dir, ".Renviron")
    if (file.exists(f)) {
      readRenviron(f)
      break
    }
    parent <- dirname(dir)
    if (identical(parent, dir)) {
      break
    }
    dir <- parent
  }
})

library(shiny)
library(ggplot2)
library(DT)

# No bslib: this app ships a bespoke, bslib-free UI (frontend-design; see
# www/app.css). The reusable component modules it composes are already Shiny-only
# (plotOutput / DTOutput / inputs), so they drop straight into custom containers;
# only the assistant is rebuilt bslib-free (byok_chat_ui_plain below) while
# reusing the byok-chat SERVER unchanged.
for (f in list.files("R/_shared", pattern = "[.][Rr]$", full.names = TRUE)) {
  source(f)
}
for (f in list.files("R/_modules", pattern = "[.][Rr]$", full.names = TRUE)) {
  source(f)
}

# --- Assistant UI, rebuilt without bslib -----------------------------------
# Reuses byok_chat_server (and the module's provider/env helpers) unchanged; only
# the presentation is bslib-free. Inputs/outputs are namespaced under `id` exactly
# as the server expects; the chat is shinychat's web component.
byok_chat_ui_plain <- function(
  id,
  title,
  subtitle = NULL,
  providers = c("gemini", "openai", "anthropic"),
  starters = NULL,
  placeholder = "Ask me anything...",
  height = "100%"
) {
  ns <- NS(id)
  providers <- .byok_chat_providers(providers)
  if (!.byok_chat_packages_ok() || length(providers) == 0) {
    return(div(
      class = "drawer-head",
      h2(title),
      div(
        class = "drawer-body",
        tags$p(
          "The AI assistant is off because its packages (ellmer, shinychat)",
          "are not installed."
        )
      )
    ))
  }
  choices <- .byok_chat_provider_choices(providers)
  greeting <- if (
    nzchar(.byok_chat_env_first(.byok_chat_provider_meta(providers[1])$env))
  ) {
    paste(
      "Hi! A key was found in your environment - open **Model & key** below,",
      "pick a model, and click **Connect** to start chatting."
    )
  } else {
    paste(
      "Hi! Open **Model & key** below, paste an API key, and click",
      "**Connect** to start chatting."
    )
  }
  if (length(starters) > 0) {
    cards <- paste0(
      "- <span class=\"suggestion submit\">",
      vapply(unname(starters), htmltools::htmlEscape, character(1)),
      "</span>"
    )
    greeting <- paste0(greeting, "\n\n", paste(cards, collapse = "\n"))
  }
  tagList(
    tags$style(HTML(paste0(
      "#",
      ns("chat"),
      " .shiny-tool-request,#",
      ns("chat"),
      " .shiny-tool-result{display:none !important;}"
    ))),
    div(
      class = "drawer-head",
      div(h2(title), if (!is.null(subtitle)) div(class = "sub", subtitle)),
      div(
        style = "display:flex;align-items:center;gap:0.6rem;",
        uiOutput(ns("conn_badge"), inline = TRUE),
        tags$button(
          class = "drawer-close",
          onclick = "SG.closeDrawer('assistant_drawer')",
          HTML("&times;")
        )
      )
    ),
    tags$details(
      class = "byok",
      tags$summary(icon("gear"), " Model & key"),
      div(
        class = "byok-body",
        selectInput(
          ns("provider"),
          "Provider",
          choices = choices,
          selected = unname(choices)[1]
        ),
        uiOutput(ns("key_help")),
        passwordInput(
          ns("api_key"),
          "API key",
          placeholder = "Paste your key (kept in this session only)"
        ),
        selectizeInput(
          ns("model"),
          "Model",
          choices = character(0),
          selected = character(0),
          multiple = FALSE,
          options = list(
            create = TRUE,
            placeholder = "Provider default - pick or type a model"
          )
        ),
        actionButton(
          ns("refresh_models"),
          "List models for this key",
          class = "btn-line"
        ),
        uiOutput(ns("model_source")),
        div(
          style = "display:flex;gap:0.5rem;margin:0.6rem 0;",
          actionButton(ns("connect"), "Connect", class = "btn-line btn-fill"),
          actionButton(ns("forget"), "Forget key", class = "btn-line")
        ),
        uiOutput(ns("cred_status"))
      )
    ),
    div(
      class = "drawer-body chat",
      shinychat::chat_ui(
        ns("chat"),
        height = height,
        placeholder = placeholder,
        greeting = greeting
      )
    )
  )
}

# Client-side glue for the bespoke UI: page nav + segmented views (plain
# show/hide, with a resize dispatch so plots redraw when revealed), slide-in
# drawers + scrim, and the upload-drawer open/close bridge to the server.
SG_JS <- paste0(
  "window.SG={",
  "_scrim:function(){return document.getElementById('scrim');},",
  "openDrawer:function(id){var d=document.getElementById(id);",
  "if(d){d.classList.add('open');SG._scrim().classList.add('show');}},",
  "closeDrawer:function(id){var d=document.getElementById(id);",
  "if(d){d.classList.remove('open');}SG._sync();},",
  "toggleDrawer:function(id){var d=document.getElementById(id);",
  "if(d&&d.classList.contains('open'))SG.closeDrawer(id);else SG.openDrawer(id);},",
  "openUpload:function(){SG.openDrawer('upload_drawer');},",
  "closeUpload:function(){SG.closeDrawer('upload_drawer');",
  "if(window.Shiny&&Shiny.setInputValue)Shiny.setInputValue('sig_upload_closed',Date.now());},",
  "closeAll:function(){var u=document.getElementById('upload_drawer');",
  "var uo=u&&u.classList.contains('open');",
  "document.querySelectorAll('.drawer.open').forEach(function(d){d.classList.remove('open');});",
  "if(uo&&window.Shiny&&Shiny.setInputValue)Shiny.setInputValue('sig_upload_closed',Date.now());SG._sync();},",
  "_sync:function(){if(!document.querySelector('.drawer.open'))SG._scrim().classList.remove('show');},",
  "_resize:function(){setTimeout(function(){window.dispatchEvent(new Event('resize'));},60);},",
  "nav:function(name){document.querySelectorAll('.navlink[data-page]').forEach(function(a){",
  "a.classList.toggle('active',a.getAttribute('data-page')===name);});",
  "document.querySelectorAll('.page-section[data-page]').forEach(function(s){",
  "s.style.display=(s.getAttribute('data-page')===name)?'block':'none';});",
  "SG._resize();window.scrollTo({top:0,behavior:'smooth'});},",
  "view:function(name){document.querySelectorAll('.seg[data-view]').forEach(function(b){",
  "b.classList.toggle('active',b.getAttribute('data-view')===name);});",
  "document.querySelectorAll('.view[data-view]').forEach(function(v){",
  "v.classList.toggle('active',v.getAttribute('data-view')===name);});SG._resize();},",
  # Demo must run on the Explorer page with no drawer covering the targets:
  # reset the UI, then fire the `demo` input once the DOM has settled.
  "startDemo:function(){SG.closeAll();SG.nav('Explorer');SG.view('smap');",
  "setTimeout(function(){if(window.Shiny&&Shiny.setInputValue)",
  "Shiny.setInputValue('demo',Date.now(),{priority:'event'});},420);}",
  "};",
  "document.addEventListener('DOMContentLoaded',function(){",
  "if(window.Shiny){Shiny.addCustomMessageHandler('open_sig_upload',function(x){SG.openUpload();});}});"
)

# The bundled Signature Scoring dataset (TCGA-BRCA + Hallmark). Users can
# instead upload their own via the offcanvas drawer, validated through the same
# contract. Labels shown in the picker.
datasets <- c(
  "Breast cancer - TCGA-BRCA (Hallmark)" = "signature-brca",
  "Upload your own…" = "__upload__"
)

# Descriptive metadata per bundled dataset, for the "About this dataset" card:
# disease/design, public source, a portal link, the primary reference + DOI, and
# licensing. Keyed by the dataset id; uploads fall back to a generic summary.
# Full provenance lives on the About page.
dataset_info <- list(
  "signature-brca" = list(
    title = "TCGA-BRCA - Hallmark pathway activity",
    design = "Primary breast tumour vs solid-tissue normal, with clinical annotations (bulk RNA-seq)",
    source = "recount3 (uniformly reprocessed TCGA RNA-seq) → VST → MSigDB Hallmark scoring",
    portal = "https://portal.gdc.cancer.gov/projects/TCGA-BRCA",
    portal_label = "GDC Data Portal - TCGA-BRCA",
    reference = "TCGA Network, Nature 490:61–70 (2012)",
    doi = "https://doi.org/10.1038/nature11412",
    license = "NIH GDS open-access (derived from recount3 summaries)"
  )
)

# Signature contract files, for the "upload your own" path.
sig_upload_files <- c(
  expression = "expression.csv",
  metadata = "metadata.csv",
  signatures = "signatures.csv"
)

# Scoring-method labels, shared by the picker and the assistant's state mirror.
method_labels <- c(
  ssgsea = "ssGSEA (single-sample)",
  singscore = "singscore (rank-based)",
  zscore = "Module score (z-score)",
  mean = "Mean expression"
)

# Grouping variables come from the dataset's metadata columns (everything but
# the sample id), with friendly labels for the known clinical columns and a
# prettified fallback for any others (e.g. an uploaded dataset's columns).
.pretty <- c(
  group = "Sample group",
  subtype = "Receptor subtype",
  er_status = "ER status",
  pr_status = "PR status",
  her2_status = "HER2 status",
  stage = "Tumor stage",
  histology = "Histology"
)
make_group_choices <- function(metadata) {
  cols <- setdiff(names(metadata), "sample")
  stats::setNames(
    cols,
    ifelse(
      cols %in% names(.pretty),
      .pretty[cols],
      tools::toTitleCase(gsub("_", " ", cols))
    )
  )
}

# Collapsible per-card guidance: a small muted toggle that expands help inline.
# Uses a native <details> element, so it needs no JS and costs no layout space
# when collapsed (the default).
card_help <- function(...) {
  tags$details(
    class = "help",
    tags$summary("How to read this"),
    div(class = "body", ...)
  )
}

# --- Bring-your-own-data drawer --------------------------------------------
# Uploads live in a custom slide-in drawer (bslib-free) rather than inline in the
# controls, so the file pickers get room and a clear column spec. The drawer
# stays mounted, so a validated upload isn't lost when it is closed. Selecting
# "Upload your own…" opens it (the server sends open_sig_upload); the close button
# tells the server (sig_upload_closed) so a cancelled upload reverts the dataset.
sig_upload_drawer <- div(
  class = "drawer",
  id = "upload_drawer",
  div(
    class = "drawer-head",
    div(
      h2("Upload your own dataset"),
      div(class = "sub", "Three CSVs matching the data contract.")
    ),
    tags$button(
      class = "drawer-close",
      onclick = "SG.closeUpload()",
      HTML("&times;")
    )
  ),
  div(
    class = "drawer-body",
    div(
      class = "drawer-copy",
      tags$p(
        "Provide three CSV files matching the signature-scoring data contract.",
        "Column names must match exactly (case-sensitive) - the dataset is",
        "rejected otherwise, with the reason shown below."
      ),
      tags$ul(
        tags$li(
          tags$code("expression.csv"),
          " - a ",
          tags$code("gene"),
          " column plus one numeric column per sample (log2-normalised)."
        ),
        tags$li(
          tags$code("metadata.csv"),
          " - one row per sample. Required columns: ",
          tags$code(toString(signature_metadata_required)),
          "."
        ),
        tags$li(
          tags$code("signatures.csv"),
          " - long form with ",
          tags$code("signature"),
          " and ",
          tags$code("gene"),
          " columns (one gene per row)."
        )
      ),
      tags$p(
        class = "muted",
        "Expression sample columns must match the metadata sample values, and",
        "at least one signature must share genes with the expression matrix."
      )
    ),
    tags$hr(),
    data_upload_validate_ui("sig_upload", sig_upload_files)
  )
)

# --- Explorer page: the interactive tool -----------------------------------
# A bespoke, bslib-free layout: the "contrast bar" signature element up top, a
# left instrument rail of global controls, and the activity-map hero (with the
# ranking table and signature volcano as sibling views) over the selected-
# signature detail row. The assistant + upload drawers live at page level (in
# `ui`) so they overlay regardless of the active view.
explorer_page <- tagList(
  # Plain-language primer: what the tool does, for a first-time (non-specialist)
  # reader, without dumbing the science down.
  div(
    class = "intro",
    div(
      class = "eyebrow",
      tags$span(class = "num", "00 ·"),
      "Pathway-activity explorer"
    ),
    div(
      class = "intro-grid",
      div(
        class = "intro-lede",
        h1(
          class = "intro-head",
          "From gene expression to pathway activity."
        ),
        tags$p(
          "Any single gene is noisy. Signature Scoring reads whole pathways ",
          "instead: it condenses each breast-cancer sample's expression into ",
          "activity scores for 50 canonical biological pathways - the MSigDB ",
          tags$em("Hallmark"),
          " collection, spanning proliferation, immune signalling, metabolism ",
          "and DNA repair - and contrasts them between clinical subtypes. The ",
          "payoff is the pathways that separate one subtype from the next, ",
          "and the genes driving each one."
        )
      ),
      div(
        class = "intro-steps",
        div(
          class = "step",
          tags$span(class = "s-n", "1"),
          div(
            tags$strong("Score"),
            tags$span("condense expression into 50 pathway scores per sample")
          )
        ),
        div(
          class = "step",
          tags$span(class = "s-n", "2"),
          div(
            tags$strong("Compare"),
            tags$span("contrast two clinical groups, e.g. HER2+ vs HR+")
          )
        ),
        div(
          class = "step",
          tags$span(class = "s-n", "3"),
          div(
            tags$strong("Drill down"),
            tags$span("open a pathway to the genes driving it")
          )
        )
      )
    )
  ),
  # Signature element: the current comparison as a diverging axis.
  div(class = "contrast-wrap", uiOutput("contrast_bar")),
  div(
    class = "layout",
    # Instrument rail: global controls.
    tags$aside(
      class = "rail",
      id = "controls_panel",
      div(
        class = "rail-head",
        div(class = "eyebrow", tags$span(class = "num", "00 ·"), "Controls")
      ),
      div(
        class = "rail-body",
        div(
          class = "rail-group",
          div(
            class = "eyebrow",
            tags$span(class = "num", "01 ·"),
            "Data & scoring"
          ),
          div(
            style = "margin-top:0.55rem;",
            selectInput("dataset", "Dataset", choices = datasets),
            conditionalPanel(
              "input.dataset == '__upload__'",
              tags$button(
                class = "btn-line",
                style = "width:100%;margin-top:0.25rem;",
                type = "button",
                onclick = "SG.openUpload()",
                "Upload / change files…"
              )
            ),
            radioButtons(
              "method",
              "Scoring method",
              choices = stats::setNames(names(method_labels), method_labels)
            )
          )
        ),
        div(
          class = "rail-group",
          div(class = "eyebrow", tags$span(class = "num", "02 ·"), "Contrast"),
          div(
            style = "margin-top:0.55rem;",
            uiOutput("group_col_ui"),
            uiOutput("contrast_ui")
          )
        ),
        div(
          class = "helptext",
          paste(
            "Signatures are scored across samples, then ranked by the chosen",
            "contrast. These controls are global - they drive the activity map,",
            "ranking, volcano and detail views. Clinical variables are",
            "tumor-only, so normals drop out of those contrasts."
          )
        )
      )
    ),
    # Content column.
    div(
      class = "stack",
      uiOutput("dataset_card"),
      div(
        class = "panel hero",
        id = "hero_panel",
        div(
          class = "panel-head",
          div(
            div(
              class = "eyebrow",
              tags$span(class = "num", "03 ·"),
              "Pathway activity"
            ),
            tags$h3(
              class = "panel-title",
              style = "margin-top:3px;",
              "Activity landscape"
            )
          )
        ),
        div(
          class = "panel-body",
          # Segmented control: custom views (no Bootstrap tabs), toggled by JS.
          div(
            class = "seg-group",
            tags$button(
              class = "seg active",
              `data-view` = "smap",
              onclick = "SG.view('smap')",
              "Sample map"
            ),
            tags$button(
              class = "seg",
              `data-view` = "map",
              onclick = "SG.view('map')",
              "Activity map"
            ),
            tags$button(
              class = "seg",
              `data-view` = "sprof",
              onclick = "SG.view('sprof')",
              "Subtype profile"
            ),
            tags$button(
              class = "seg",
              `data-view` = "pcorr",
              onclick = "SG.view('pcorr')",
              "Program correlation"
            ),
            tags$button(
              class = "seg",
              `data-view` = "rank",
              onclick = "SG.view('rank')",
              "Ranking"
            ),
            tags$button(
              class = "seg",
              `data-view` = "volc",
              onclick = "SG.view('volc')",
              "Volcano"
            )
          ),
          div(
            class = "views",
            div(
              class = "view active",
              `data-view` = "smap",
              card_help(
                "Every sample placed by its Hallmark-activity profile (PCA of",
                "the score matrix): samples with similar pathway activity sit",
                "close together. Points are coloured by the chosen grouping, so",
                "you can see whether subtypes separate by program activity -",
                "something a gene-level DE analysis cannot show. Click a point",
                "to load that sample's fingerprint below."
              ),
              plotOutput(
                "sample_map",
                height = "560px",
                click = "sample_map_click"
              )
            ),
            div(
              class = "view",
              `data-view` = "map",
              card_help(
                "Signature scores across the contrasted samples, row z-scored",
                "so activity patterns are comparable across signatures;",
                "clustering reorders rows by similarity. Columns are the",
                "samples, coloured by group. Choose how many top signatures",
                "to show."
              ),
              div(
                style = "display:flex;justify-content:flex-end;margin-bottom:0.5rem;",
                selectInput(
                  "ntop",
                  "Signatures shown",
                  choices = c("15", "25", "50"),
                  selected = "25",
                  width = "180px"
                )
              ),
              heatmap_ui("heat")
            ),
            div(
              class = "view",
              `data-view` = "sprof",
              card_help(
                "Mean pathway activity in each group, row z-scored across",
                "groups and clustered - a compact molecular portrait showing",
                "which programs define each subtype."
              ),
              plotOutput("subtype_profile", height = "640px")
            ),
            div(
              class = "view",
              `data-view` = "pcorr",
              card_help(
                "How the 50 Hallmark programs co-vary across samples (Pearson",
                "correlation of the scores), clustered so co-activated modules",
                "form blocks along the diagonal."
              ),
              plotOutput("program_corr", height = "640px")
            ),
            div(
              class = "view",
              `data-view` = "rank",
              card_help(
                "Every signature's mean score in each group, their",
                "difference, and a two-sample t-test (BH-adjusted). Select a",
                "row to inspect that signature in the detail views below."
              ),
              DT::DTOutput("ranking", fill = FALSE)
            ),
            div(
              class = "view",
              `data-view` = "volc",
              card_help(
                "Each point is a Hallmark signature: the score difference",
                "between your two groups (x) vs -log10 p (y). The dashed line",
                "marks your significance threshold. Colour marks direction."
              ),
              div(
                style = "display:grid;grid-template-columns:1fr 1fr;gap:1rem;",
                sliderInput(
                  "vp",
                  "Significance threshold",
                  min = 0.001,
                  max = 0.1,
                  value = 0.05,
                  step = 0.001
                ),
                sliderInput(
                  "vlabels",
                  "Max labels",
                  min = 0,
                  max = 25,
                  value = 10,
                  step = 1
                )
              ),
              volcano_ui("volcano")
            )
          )
        )
      ),
      div(
        class = "row-2",
        div(
          class = "panel",
          id = "hdr-detail",
          div(
            class = "panel-head",
            div(
              class = "eyebrow",
              tags$span(class = "num", "04 ·"),
              "Signature detail"
            )
          ),
          div(
            class = "panel-body",
            card_help(
              "The selected signature's per-sample scores, split by group.",
              "Select a row in the Ranking view to change which signature shows."
            ),
            uiOutput("detail_sig_label"),
            group_comparison_ui("detail")
          )
        ),
        div(
          class = "panel",
          id = "hdr-genes",
          div(
            class = "panel-head",
            div(
              class = "eyebrow",
              tags$span(class = "num", "05 ·"),
              textOutput("le_title", inline = TRUE)
            )
          ),
          div(
            class = "panel-body",
            card_help(
              "The member genes of the selected signature, ranked by their",
              "between-group expression difference - the genes driving the",
              "signature's shift. The heatmap shows the top genes; the table",
              "lists them all."
            ),
            heatmap_ui("genes"),
            DT::DTOutput("leading_edge", fill = FALSE)
          )
        )
      ),
      div(
        class = "row-2",
        div(
          class = "panel",
          id = "hdr-markers",
          div(
            class = "panel-head",
            div(
              class = "eyebrow",
              tags$span(class = "num", "06 ·"),
              "Subtype markers"
            )
          ),
          div(
            class = "panel-body",
            card_help(
              "For the chosen group, the Hallmark programs whose activity is",
              "most elevated or depressed versus every other sample",
              "(one-vs-rest Wilcoxon) - the programs that define a subtype."
            ),
            uiOutput("marker_subtype_ui"),
            plotOutput("subtype_markers", height = "460px")
          )
        ),
        div(
          class = "panel",
          id = "hdr-fingerprint",
          div(
            class = "panel-head",
            div(
              class = "eyebrow",
              tags$span(class = "num", "07 ·"),
              "Sample fingerprint"
            )
          ),
          div(
            class = "panel-body",
            card_help(
              "One sample's pathway activity as a z-score against the whole",
              "cohort - its most and least active programs. Pick a sample,",
              "or click a point in the Sample map above."
            ),
            uiOutput("fp_sample_ui"),
            plotOutput("sample_fp", height = "460px")
          )
        )
      )
    )
  )
)

# --- About page: orientation + documentation -------------------------------
# One page: a quick orientation (what the tool does, how to start) followed by
# the reference material (data provenance, citations, methods, credits).
about_page <- div(
  class = "about",
  markdown(
    "## Signature Scoring Explorer

Score MSigDB **Hallmark** gene sets across samples and compare pathway activity
between groups - from a whole-collection overview down to the genes driving one
signature. Part of the **Lifescience Shiny Gallery**: reusable Shiny apps and
components for common bioinformatics workflows.

#### What you can do
- **Activity map** - the whole Hallmark collection scored across samples, the
  spotlight view of the app.
- **Ranking** - mean score per group, difference, and a per-signature t-test.
- **Signature volcano** - every signature's group difference vs significance.
- **Signature detail** - a selected signature's scores across sample groups.
- **Pathway genes** - the selected signature's leading-edge member genes.

#### Getting started
On the **Explorer** tab, pick a scoring method and a group contrast in the
**Controls** sidebar. The activity map is front and centre, with the Ranking
table and signature Volcano a tab away; selecting a row in the Ranking tab drives
the Signature detail and Pathway genes views. Open the **Assistant** from the top
bar to ask about any view or have it drive the controls.

### Data
- **TCGA-BRCA** (`signature-brca`) - The Cancer Genome Atlas breast-invasive-
  carcinoma cohort: primary tumour vs solid-tissue normal, with clinical
  annotations (receptor subtype, ER / PR / HER2 status, stage, histology).
  Counts come from **recount3**, which uniformly re-aligns and quantifies public
  RNA-seq, so samples are directly comparable. We take VST-log2 expression and
  score the **MSigDB Hallmark** collection (50 gene sets). A curated subset -
  75 tumours balanced across the HR+ / HER2+ / TNBC receptor subtypes (25 each)
  plus 20 solid-tissue normal - ships with the app for a fast, reproducible demo
  with real subtyping power.

Prep scripts under `data/prep/` are the source of truth (provenance + licensing).

#### Citations
- TCGA Network. *Comprehensive molecular portraits of human breast tumours.*
  Nature 490:61–70 (2012). doi:10.1038/nature11412
- Wilks C, et al. *recount3: summaries and queries for large-scale RNA-seq
  expression and splicing.* Genome Biol 22:323 (2021).
  doi:10.1186/s13059-021-02533-6
- Liberzon A, et al. *The Molecular Signatures Database Hallmark gene set
  collection.* Cell Syst 1:417–425 (2015). doi:10.1016/j.cels.2015.12.004
- Barbie DA, et al. *Systematic RNA interference reveals that oncogenic
  KRAS-driven cancers require TBK1.* Nature 462:108–112 (2009).
  doi:10.1038/nature08460 (ssGSEA)
- Foroutan M, et al. *Single sample scoring of molecular phenotypes.* BMC
  Bioinformatics 19:404 (2018). doi:10.1186/s12859-018-2435-4 (singscore)

TCGA data are subject to the [NIH Genomic Data Sharing Policy](https://gdc.cancer.gov/access-data/data-access-policies);
the processed subset here is derived from open-access recount3 summaries.

### Methods
- **Scoring** reduces the expression matrix + gene sets to per-sample signature
  scores by one of four dependency-free methods: **ssGSEA** (Barbie 2009),
  **singscore** (rank-based, Foroutan 2018), a **module z-score**, or the
  **mean** of the set's genes.
- **Ranking / volcano** contrast two groups per signature (difference in mean
  score + a two-sample t-test, BH-adjusted across signatures).
- **Score heatmap** shows the top signatures' scores, row z-scored and clustered.
- **Pathway genes** rank a signature's member genes by their between-group
  expression difference (its leading edge).

### Bring your own data
Match the signature-scoring data contract - `expression.csv`, `metadata.csv`,
`signatures.csv` - and choose *Upload your own…* in the dataset picker. See the
data-contract and reuse guides under the repository `docs/`.

### Credits
Built with **Shiny**. MIT © 2026 Posit Software, PBC. Authored by Samuel Bharti."
  )
)

ui <- tagList(
  tags$head(
    tags$meta(
      name = "viewport",
      content = "width=device-width, initial-scale=1"
    ),
    tags$title("Signature Scoring"),
    tags$link(rel = "preconnect", href = "https://fonts.googleapis.com"),
    tags$link(
      rel = "preconnect",
      href = "https://fonts.gstatic.com",
      crossorigin = NA
    ),
    tags$link(
      rel = "stylesheet",
      href = paste0(
        # Fraunces (optical serif) for the display voice, Libre Franklin for
        # UI/body, JetBrains Mono for data/labels.
        "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,",
        "500..700&family=Libre+Franklin:wght@400;500;600;700",
        "&family=JetBrains+Mono:wght@400;500&display=swap"
      )
    ),
    tags$link(
      rel = "stylesheet",
      href = paste0(
        "app.css?v=",
        as.integer(file.info("www/app.css")$mtime)
      )
    ),
    # shinychat's version gate reads window.bootstrap.Tab.VERSION; load Bootstrap
    # 5's JS bundle (a plain CDN script, not bslib) so the gate is satisfied,
    # while shiny-core Bootstrap 3 keeps driving the tab switching.
    tags$script(
      src = paste0(
        "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/",
        "bootstrap.bundle.min.js"
      )
    ),
    tags$script(HTML(SG_JS))
  ),
  cicerone::use_cicerone(),
  # Top bar: wordmark + page nav (Explorer / About) + utilities.
  div(
    class = "topbar",
    div(
      class = "brand",
      tags$span(class = "tick", HTML("&#9670;")),
      "Signature Scoring",
      tags$small("Hallmark activity")
    ),
    div(
      class = "topnav",
      tags$a(
        class = "navlink active",
        `data-page` = "Explorer",
        onclick = "SG.nav('Explorer', this)",
        "Explorer"
      ),
      tags$a(
        class = "navlink",
        `data-page` = "About",
        onclick = "SG.nav('About', this)",
        "About"
      ),
      div(class = "spacer"),
      tags$a(
        class = "navlink",
        id = "open_assistant",
        onclick = "SG.toggleDrawer('assistant_drawer')",
        icon("robot"),
        "Assistant"
      ),
      tags$a(
        class = "navlink",
        onclick = "SG.startDemo()",
        icon("circle-play"),
        "Demo"
      ),
      tags$a(
        class = "navlink",
        href = "https://github.com/posit-dev/lifescience-shiny-gallery",
        target = "_blank",
        rel = "noopener",
        icon("github"),
        "Source"
      )
    )
  ),
  # Page sections toggled by the top-bar nav (SG.nav dispatches a resize so any
  # newly revealed plots redraw).
  div(
    class = "page",
    div(
      class = "page-section",
      `data-page` = "Explorer",
      style = "display:block;",
      explorer_page
    ),
    div(
      class = "page-section",
      `data-page` = "About",
      style = "display:none;",
      about_page
    )
  ),
  div(
    class = "footer",
    "Signature Scoring · MIT © 2026 Posit Software, PBC · Authored by Samuel Bharti"
  ),
  # Page-level overlays: scrim + the assistant and upload drawers.
  div(id = "scrim", class = "scrim", onclick = "SG.closeAll()"),
  div(
    class = "drawer",
    id = "assistant_drawer",
    byok_chat_ui_plain(
      "chat",
      title = "Signature Scoring assistant",
      subtitle = "Bring your own Gemini / OpenAI / Anthropic key.",
      height = "100%",
      starters = c(
        "Summarise this dataset and its clinical variables.",
        "Which Hallmark signatures differ most between tumor and normal?",
        "Switch to singscore and re-rank the signatures.",
        "Contrast ER-positive vs ER-negative tumors.",
        "Focus HALLMARK_E2F_TARGETS and explain its leading-edge genes.",
        "Show the 50 most differential signatures in the heatmap."
      )
    )
  ),
  sig_upload_drawer
)

server <- function(input, output, session) {
  # --- Guided demo tour (the "Demo" button in the navbar) -----------------
  # Walks a first-time user through the whole app: the input controls, then each
  # analysis card (highlighting its header), the assistant, and finally the
  # About page (cicerone switches to that nav tab for the last step).
  demo_guide <- cicerone::Cicerone$new(overlay_click_next = TRUE)$step(
    "controls_panel",
    "1. Choose your data",
    paste(
      "Start here: pick a dataset, a scoring method, and the two groups to",
      "contrast. These are global and drive every view."
    )
  )$step(
    "contrast_bar",
    "The contrast",
    "Your comparison as a diverging axis: the two groups being contrasted and their sample counts. It restyles as you change the grouping variable or levels."
  )$step(
    "dataset_card",
    "About this dataset",
    "A quick summary of the loaded cohort: design, sample counts, signatures, source, and a link to the data portal."
  )$step(
    "hero_panel",
    "Pathway activity",
    "The heart of the app. The Sample map places each sample by its pathway-activity profile (subtypes separate here); the Activity map is the samples x signatures heatmap; Ranking and Volcano contrast two groups. Selecting a Ranking row drives the detail views below."
  )$step(
    "hdr-detail",
    "Signature detail",
    "The selected signature's per-sample scores, split by group, with a group-comparison test."
  )$step(
    "hdr-genes",
    "Pathway genes",
    "The selected signature's member genes ranked by between-group expression difference - the genes driving its shift."
  )$step(
    "open_assistant",
    "AI assistant",
    "Open the assistant (bring your own API key) to ask about any view, or have it drive the controls for you."
  )$step(
    "a.navlink[data-page='About']",
    "Learn more",
    "Finally, open the About page for full data provenance, methods, and citations. That's the tour!",
    is_id = FALSE
  )
  observeEvent(input$demo, demo_guide$init()$start())

  # --- Signature element: the contrast rendered as a diverging axis --------
  output$contrast_bar <- renderUI({
    m <- metadata()
    gc <- input$group_col %||% "group"
    l1 <- input$level1
    l2 <- input$level2
    if (is.null(l1) || is.null(l2) || !gc %in% names(m)) {
      return(NULL)
    }
    n1 <- sum(as.character(m[[gc]]) == l1, na.rm = TRUE)
    n2 <- sum(as.character(m[[gc]]) == l2, na.rm = TRUE)
    choices <- make_group_choices(m)
    glabel <- names(choices)[match(gc, choices)] %||% gc
    meth <- unname(
      method_labels[match(input$method %||% "ssgsea", names(method_labels))]
    )
    div(
      class = "contrast",
      div(
        class = "eyebrow",
        tags$span(class = "num", "01 ·"),
        paste0("Contrast · ", glabel)
      ),
      div(
        class = "contrast-axis",
        div(
          class = "c-side ref",
          tags$span(class = "c-name", l1),
          tags$span(class = "c-n", paste0("n = ", n1))
        ),
        div(
          class = "c-track",
          tags$span(class = "rail"),
          tags$span(class = "zero"),
          tags$span(class = "cap l", HTML("&#9664;")),
          tags$span(class = "cap r", HTML("&#9654;"))
        ),
        div(
          class = "c-side cmp",
          tags$span(class = "c-name", l2),
          tags$span(class = "c-n", paste0("n = ", n2))
        )
      ),
      div(
        class = "contrast-meta",
        paste0(
          meth,
          "  ·  ",
          length(signatures()),
          " Hallmark sets  ·  difference = ",
          l2,
          " - ",
          l1
        )
      )
    )
  })

  # One signature dataset: the bundled contract dir, or the user's uploaded
  # CSVs (validated through the same contract). Everything downstream is
  # reactive on it, so an upload swaps the whole analysis.
  uploaded <- data_upload_validate_server(
    "sig_upload",
    reader = read_signature_dataset,
    files = sig_upload_files
  )
  dataset <- reactive({
    if (identical(input$dataset, "__upload__")) {
      req(uploaded())
      uploaded()
    } else {
      read_signature_dataset("data")
    }
  })
  expr <- reactive(signature_expression_matrix(dataset()))
  metadata <- reactive(dataset()$metadata)
  signatures <- reactive(dataset()$signatures)

  # Bring-your-own-data drawer wiring. Selecting "Upload your own…" opens the
  # offcanvas; the bundled dataset is remembered so a cancelled upload can fall
  # back to it rather than leaving the app on an empty "__upload__" selection.
  prev_dataset <- reactiveVal(unname(datasets[[1]]))
  observeEvent(input$dataset, {
    if (identical(input$dataset, "__upload__")) {
      session$sendCustomMessage("open_sig_upload", TRUE)
    } else {
      prev_dataset(input$dataset)
    }
  })
  observeEvent(input$sig_upload_closed, {
    if (identical(input$dataset, "__upload__") && is.null(uploaded())) {
      updateSelectInput(session, "dataset", selected = prev_dataset())
    }
  })

  # Grouping-variable picker, rebuilt from the current dataset's metadata.
  output$group_col_ui <- renderUI({
    ch <- make_group_choices(metadata())
    # Lead with the subtyping story: default to a clinical subtype column when
    # the dataset has one.
    sel <- if ("subtype" %in% ch) "subtype" else unname(ch)[1]
    selectInput("group_col", "Group samples by", choices = ch, selected = sel)
  })

  # --- Sample map: samples embedded in Hallmark-activity space (PCA) --------
  # Reuses the shared pca_data() + plot_pca() logic, fed the signature-score
  # matrix instead of gene expression, so proximity reflects shared pathway
  # activity. Coloured by the chosen grouping (subtype by default) - the view
  # DE cannot produce. Clicking a point loads that sample's fingerprint.
  sample_map_pca <- reactive({
    sc <- scores()
    shiny::validate(shiny::need(
      ncol(sc) >= 3,
      "Need at least 3 samples for a sample map."
    ))
    pca_data(sc, metadata = metadata(), n_top = Inf)
  })
  output$sample_map <- renderPlot(
    plot_pca(sample_map_pca(), colour_by = input$group_col %||% "group"),
    res = 96
  )
  observeEvent(input$sample_map_click, {
    np <- nearPoints(
      sample_map_pca()$scores,
      input$sample_map_click,
      xvar = "PC1",
      yvar = "PC2",
      maxpoints = 1
    )
    if (nrow(np) > 0) {
      updateSelectInput(session, "fp_sample", selected = np$sample)
    }
  })

  # --- Subtype profile: mean activity per group (a molecular portrait) ------
  output$subtype_profile <- renderPlot(
    {
      gv <- group_vec()
      shiny::validate(shiny::need(
        length(unique(stats::na.omit(gv))) >= 2,
        "Choose a grouping with at least two labelled groups."
      ))
      mat <- summarise_scores_by_group(scores(), gv)
      z <- t(scale(t(mat)))
      ord <- stats::hclust(stats::dist(z))$order
      z <- z[ord, , drop = FALSE]
      labs <- tolower(gsub("_", " ", sub("^HALLMARK_", "", rownames(z))))
      df <- data.frame(
        signature = factor(rep(labs, ncol(z)), levels = labs),
        group = factor(rep(colnames(z), each = nrow(z)), levels = colnames(z)),
        z = as.vector(z)
      )
      ggplot2::ggplot(df, ggplot2::aes(group, signature, fill = z)) +
        ggplot2::geom_tile(colour = "white", linewidth = 0.4) +
        ggplot2::scale_fill_gradientn(
          colours = ltc_gradient(),
          name = "row z"
        ) +
        ggplot2::labs(x = NULL, y = NULL) +
        ggplot2::theme_minimal(base_size = 13) +
        ggplot2::theme(
          axis.text.y = ggplot2::element_text(size = 9),
          axis.text.x = ggplot2::element_text(face = "bold"),
          panel.grid = ggplot2::element_blank()
        )
    },
    res = 96
  )

  # --- Program correlation: which signatures co-activate --------------------
  output$program_corr <- renderPlot(
    {
      cm <- signature_correlation(scores())
      ord <- stats::hclust(stats::as.dist(1 - cm))$order
      cm <- cm[ord, ord]
      labs <- tolower(gsub("_", " ", sub("^HALLMARK_", "", rownames(cm))))
      df <- expand.grid(x = seq_along(labs), y = seq_along(labs))
      df$r <- as.vector(cm)
      ggplot2::ggplot(df, ggplot2::aes(x, y, fill = r)) +
        ggplot2::geom_tile() +
        ggplot2::scale_fill_gradient2(
          low = "#2c6b8f",
          mid = "#f2efe6",
          high = "#c4562f",
          midpoint = 0,
          limits = c(-1, 1),
          name = "cor"
        ) +
        ggplot2::scale_x_continuous(
          breaks = seq_along(labs),
          labels = labs,
          expand = c(0, 0)
        ) +
        ggplot2::scale_y_continuous(
          breaks = seq_along(labs),
          labels = labs,
          expand = c(0, 0)
        ) +
        ggplot2::coord_fixed() +
        ggplot2::labs(x = NULL, y = NULL) +
        ggplot2::theme_minimal(base_size = 11) +
        ggplot2::theme(
          axis.text.x = ggplot2::element_text(
            angle = 90,
            hjust = 1,
            vjust = 0.5,
            size = 7
          ),
          axis.text.y = ggplot2::element_text(size = 7),
          panel.grid = ggplot2::element_blank()
        )
    },
    res = 96
  )

  # --- Subtype markers: one-vs-rest programs specific to a group ------------
  output$marker_subtype_ui <- renderUI({
    levs <- contrast_levels()
    selectInput("marker_subtype", "Group", choices = levs, selected = levs[1])
  })
  output$subtype_markers <- renderPlot(
    {
      req(input$marker_subtype)
      gv <- group_vec()
      shiny::validate(shiny::need(
        input$marker_subtype %in%
          gv &&
          sum(gv != input$marker_subtype, na.rm = TRUE) > 0,
        "Need the chosen group and at least one other sample."
      ))
      mk <- signature_group_markers(scores(), gv, input$marker_subtype)
      top <- utils::head(mk[order(-abs(mk$diff)), , drop = FALSE], 15)
      top$label <- tolower(gsub("_", " ", sub("^HALLMARK_", "", top$signature)))
      top$label <- factor(top$label, levels = top$label[order(top$diff)])
      top$sig <- ifelse(
        !is.na(top$padj) & top$padj <= 0.05,
        "padj <= 0.05",
        "ns"
      )
      ggplot2::ggplot(top, ggplot2::aes(diff, label)) +
        ggplot2::geom_segment(
          ggplot2::aes(x = 0, xend = diff, y = label, yend = label),
          colour = "#c9d2cc"
        ) +
        ggplot2::geom_point(ggplot2::aes(colour = sig), size = 3.2) +
        ggplot2::scale_colour_manual(
          values = c("padj <= 0.05" = "#3f5a2a", "ns" = "#b8bfc0"),
          name = NULL
        ) +
        ggplot2::geom_vline(xintercept = 0, colour = "#8a948e") +
        ggplot2::labs(
          x = sprintf("mean score: %s vs rest", input$marker_subtype),
          y = NULL
        ) +
        ggplot2::theme_minimal(base_size = 13) +
        ggplot2::theme(panel.grid.major.y = ggplot2::element_blank())
    },
    res = 96
  )

  # --- Sample fingerprint: a sample's top up/down programs ------------------
  output$fp_sample_ui <- renderUI({
    ch <- colnames(scores())
    selectInput("fp_sample", "Sample", choices = ch, selected = ch[1])
  })
  output$sample_fp <- renderPlot(
    {
      req(input$fp_sample)
      shiny::validate(shiny::need(
        input$fp_sample %in% colnames(scores()),
        "Pick a sample."
      ))
      fp <- sample_fingerprint(scores(), input$fp_sample)
      top <- rbind(utils::head(fp, 10), utils::tail(fp, 10))
      top$label <- tolower(gsub("_", " ", sub("^HALLMARK_", "", top$signature)))
      top$label <- factor(top$label, levels = top$label[order(top$z)])
      top$dir <- ifelse(top$z >= 0, "up", "down")
      ggplot2::ggplot(top, ggplot2::aes(z, label, colour = dir)) +
        ggplot2::geom_segment(
          ggplot2::aes(x = 0, xend = z, y = label, yend = label),
          colour = "#c9d2cc"
        ) +
        ggplot2::geom_point(size = 3.2) +
        ggplot2::scale_colour_manual(
          values = c(up = "#c4562f", down = "#2c6b8f"),
          guide = "none"
        ) +
        ggplot2::geom_vline(xintercept = 0, colour = "#8a948e") +
        ggplot2::labs(
          x = sprintf("pathway activity (z vs cohort) - %s", input$fp_sample),
          y = NULL
        ) +
        ggplot2::theme_minimal(base_size = 13) +
        ggplot2::theme(panel.grid.major.y = ggplot2::element_blank())
    },
    res = 96
  )

  # signatures x samples score matrix, recomputed when the method changes.
  scores <- reactive(
    score_signatures(expr(), signatures(), method = input$method)
  )
  group_vec <- reactive({
    req(input$group_col)
    metadata()[[input$group_col]][match(colnames(scores()), metadata()$sample)]
  })

  # Non-NA levels of the chosen grouping column, and the two-level contrast
  # pickers seeded with the first two.
  contrast_levels <- reactive({
    req(input$group_col)
    sort(unique(stats::na.omit(as.character(metadata()[[input$group_col]]))))
  })
  output$contrast_ui <- renderUI({
    levs <- contrast_levels()
    shiny::validate(shiny::need(
      length(levs) >= 2,
      "This grouping variable needs at least two levels to contrast."
    ))
    tagList(
      selectInput("level1", "Reference", choices = levs, selected = levs[1]),
      selectInput("level2", "Compared with", choices = levs, selected = levs[2])
    )
  })

  # Signatures ranked by the chosen two-group contrast (most significant first).
  ranking <- reactive({
    l1 <- req(input$level1)
    l2 <- req(input$level2)
    shiny::validate(shiny::need(
      l1 != l2,
      "Pick two different groups to contrast."
    ))
    rank_signatures(scores(), group_vec(), group1 = l1, group2 = l2)
  })

  # The samples in the current contrast (drops the rest, e.g. NA-annotated
  # normals when contrasting a tumor-only clinical variable). The heatmap and
  # detail views focus on these so they stay consistent with the ranking.
  contrast_meta <- reactive({
    req(input$group_col, input$level1, input$level2)
    m <- metadata()
    m[
      as.character(m[[input$group_col]]) %in% c(input$level1, input$level2),
      ,
      drop = FALSE
    ]
  })
  contrast_scores <- reactive({
    scores()[, colnames(scores()) %in% contrast_meta()$sample, drop = FALSE]
  })

  # --- About this dataset: disease/design, size, source, reference, links ---
  output$dataset_card <- renderUI({
    meta <- metadata()
    n <- nrow(meta)
    grp <- if ("group" %in% names(meta)) table(meta$group) else NULL
    grp_txt <- if (!is.null(grp)) {
      paste(sprintf("%s (n=%d)", names(grp), as.integer(grp)), collapse = ", ")
    }
    cols <- setdiff(names(meta), "sample")
    info <- dataset_info[[input$dataset]]
    if (is.null(info)) {
      info <- list(
        title = "Your uploaded dataset",
        design = NULL,
        source = "User-provided CSVs (matching the signature data contract)",
        portal = NULL,
        portal_label = NULL,
        reference = NULL,
        doi = NULL,
        license = NULL
      )
    }
    line <- function(label, value) {
      if (is.null(value)) {
        NULL
      } else {
        tags$p(
          class = "ds-line",
          tags$span(class = "ds-k", label),
          tags$span(class = "ds-v", value)
        )
      }
    }
    div(
      class = "panel",
      div(
        class = "panel-head",
        div(
          div(class = "eyebrow", tags$span(class = "num", "·"), "Dataset"),
          tags$h3(
            class = "panel-title",
            style = "margin-top:3px;",
            info$title
          )
        )
      ),
      div(
        class = "panel-body",
        div(
          class = "ds-grid",
          div(
            line("Design", info$design),
            tags$p(
              class = "ds-line",
              tags$span(class = "ds-k", "Samples"),
              tags$span(
                class = "ds-v",
                paste0(n, if (!is.null(grp_txt)) paste0(" · ", grp_txt) else "")
              )
            ),
            tags$p(
              class = "ds-line",
              tags$span(class = "ds-k", "Signatures"),
              tags$span(
                class = "ds-v",
                paste0(length(signatures()), " Hallmark gene sets")
              )
            ),
            line("Metadata", paste(cols, collapse = ", "))
          ),
          div(
            line("Source", info$source),
            if (!is.null(info$reference)) {
              tags$p(
                class = "ds-line",
                tags$span(class = "ds-k", "Reference"),
                tags$span(
                  class = "ds-v",
                  info$reference,
                  if (!is.null(info$doi)) {
                    tagList(
                      " ",
                      tags$a(
                        href = info$doi,
                        target = "_blank",
                        rel = "noopener",
                        "DOI"
                      )
                    )
                  }
                )
              )
            },
            line("License", info$license)
          )
        ),
        div(
          class = "ds-actions",
          if (!is.null(info$portal)) {
            tags$a(
              href = info$portal,
              target = "_blank",
              rel = "noopener",
              class = "btn-line",
              icon("up-right-from-square"),
              paste0(" ", info$portal_label %||% "Data portal")
            )
          },
          tags$a(
            class = "ds-more",
            onclick = "SG.nav('About')",
            "Read more on the About page →"
          )
        )
      )
    )
  })

  # --- Assistant: scoped, tool-using BYOK chat ----------------------------
  # A plain (non-reactive) mirror of the app's current state. The assistant's
  # tools read it directly, so they are safe to call mid-stream (outside any
  # reactive context); it is kept current by an observer at the end of server().
  chat_state <- new.env(parent = emptyenv())

  # Compact "g" p-value formatting for the read tools.
  .fmt_p <- function(x) formatC(x, format = "g", digits = 3)

  # Hard-scoped: the assistant only helps with THIS app + dataset, reads live
  # state through its tools, and declines anything off-topic.
  sig_system_prompt <- paste(
    "You are the Signature Scoring assistant, embedded in an app that scores",
    "MSigDB Hallmark gene sets across samples of one loaded dataset (e.g.",
    "TCGA-BRCA tumour vs normal, with clinical annotations) and ranks the",
    "signatures between two groups. Your ONLY job is to help the user explore",
    "and interpret THIS app: its current dataset, scoring method, and contrast,",
    "and its views -- the signature volcano, the ranking table, signature",
    "detail, the score heatmap, and the leading-edge (pathway) genes.",
    "",
    "Before answering about a view, call the matching read tool for its live",
    "state: dataset_info, describe_ranking, describe_volcano, describe_signature,",
    "describe_leading_edge. Never invent signature names, gene names, counts, or",
    "statistics -- quote the tool output. Explain single-sample pathway-activity",
    "scores (ssGSEA, singscore, module z-score, mean), score differences,",
    "p-values, and Hallmark pathway terms plainly.",
    "",
    "You can also DRIVE the app's controls when the user asks -- then briefly say",
    "what you changed:",
    "- set_method: change the scoring method (re-scores every signature).",
    "- set_contrast: change the grouping variable and/or the two levels being",
    "  contrasted (drives the ranking, volcano, heatmap, and detail together).",
    "- set_signature: focus a signature in Signature detail and Pathway genes.",
    "- set_signature_count: how many top signatures the score heatmap shows.",
    "- set_volcano: the volcano's significance threshold and label count.",
    "After changing a control, you may re-read the relevant view to interpret it.",
    "",
    "Refuse anything outside this app and dataset: for off-topic or general",
    "questions, briefly decline and point back to what the app can do. Be concise.",
    sep = "\n"
  )

  # Read/interpret tools over the state mirror, plus control tools that drive the
  # inputs (guarded so the app still loads without ellmer). Each read tool
  # returns a compact summary computed from the mirrored state.
  sig_tools <- list()
  if (requireNamespace("ellmer", quietly = TRUE)) {
    sig_tools <- list(
      ellmer::tool(
        function() {
          meta <- chat_state$dataset$metadata
          grp <- if ("group" %in% names(meta)) table(meta$group) else NULL
          paste(
            c(
              paste0("Dataset: ", chat_state$dataset_label, "."),
              paste0(
                "Samples: ",
                nrow(meta),
                "; genes measured: ",
                nrow(chat_state$dataset$expression),
                "; Hallmark signatures: ",
                length(chat_state$dataset$signatures),
                "."
              ),
              if (!is.null(grp)) {
                paste0(
                  "Sample groups: ",
                  paste(
                    sprintf("%s (n=%d)", names(grp), as.integer(grp)),
                    collapse = ", "
                  ),
                  "."
                )
              },
              paste0(
                "Metadata columns: ",
                paste(setdiff(names(meta), "sample"), collapse = ", "),
                "."
              ),
              paste0("Scoring method: ", chat_state$method_label, "."),
              paste0(
                "Current contrast: ",
                chat_state$group_label %||% chat_state$group_col,
                " (",
                chat_state$level2,
                " vs ",
                chat_state$level1,
                ")."
              )
            ),
            collapse = "\n"
          )
        },
        name = "dataset_info",
        description = paste(
          "Meta on the loaded dataset: sample / gene / signature counts, groups,",
          "metadata columns, the current scoring method, and the current",
          "group contrast."
        )
      ),
      ellmer::tool(
        function() {
          r <- chat_state$ranking
          if (is.null(r) || nrow(r) == 0) {
            return("No ranking is available yet (pick two contrast levels).")
          }
          sig <- r[!is.na(r$padj) & r$padj <= chat_state$vp, , drop = FALSE]
          join <- function(d) {
            if (nrow(d) == 0) {
              return("(none)")
            }
            paste(
              sprintf(
                "%s (diff %.2f, padj %s)",
                d$signature,
                d$diff,
                .fmt_p(d$padj)
              ),
              collapse = "; "
            )
          }
          up2 <- utils::head(sig[order(-sig$diff), , drop = FALSE], 6)
          up1 <- utils::head(sig[order(sig$diff), , drop = FALSE], 6)
          paste(
            sprintf(
              "Contrast %s vs %s (diff = %s - %s); method %s.",
              chat_state$level2,
              chat_state$level1,
              chat_state$level2,
              chat_state$level1,
              chat_state$method_label
            ),
            sprintf(
              "%d of %d signatures are significant at padj <= %g.",
              nrow(sig),
              nrow(r),
              chat_state$vp
            ),
            paste0("Higher in ", chat_state$level2, ": ", join(up2), "."),
            paste0("Higher in ", chat_state$level1, ": ", join(up1), "."),
            sep = "\n"
          )
        },
        name = "describe_ranking",
        description = paste(
          "Ranking summary: how many signatures are significant at the current",
          "threshold, and the signatures most elevated in each of the two groups."
        )
      ),
      ellmer::tool(
        function() {
          r <- chat_state$ranking
          if (is.null(r) || nrow(r) == 0) {
            return("No signatures are scored yet.")
          }
          r <- r[!is.na(r$diff) & !is.na(r$padj), , drop = FALSE]
          sig <- r[r$padj <= chat_state$vp, , drop = FALSE]
          join <- function(d) {
            if (nrow(d) == 0) "(none)" else paste(d$signature, collapse = ", ")
          }
          paste(
            sprintf(
              "Volcano over %d scored signatures at padj <= %g (%s vs %s).",
              nrow(r),
              chat_state$vp,
              chat_state$level2,
              chat_state$level1
            ),
            sprintf("Significant: %d.", nrow(sig)),
            paste0(
              "Most significant: ",
              join(utils::head(sig[order(sig$padj), , drop = FALSE], 8)),
              "."
            ),
            paste0(
              "Largest score differences: ",
              join(utils::head(sig[order(-abs(sig$diff)), , drop = FALSE], 8)),
              "."
            ),
            sep = "\n"
          )
        },
        name = "describe_volcano",
        description = paste(
          "Volcano summary: how many signatures are significant, the most",
          "significant signatures, and the largest score differences."
        )
      ),
      ellmer::tool(
        function() {
          sig <- chat_state$selected_sig
          r <- chat_state$ranking
          if (is.null(sig) || is.null(r)) {
            return("No signature is selected yet.")
          }
          row <- r[r$signature == sig, , drop = FALSE]
          if (nrow(row) == 0) {
            return(paste0("'", sig, "' is not in the current ranking."))
          }
          mean_cols <- grep("^mean_", names(r), value = TRUE)
          means <- paste(
            sprintf(
              "%s = %.3f",
              sub("^mean_", "mean ", mean_cols),
              as.numeric(row[mean_cols])
            ),
            collapse = "; "
          )
          paste0(
            "Selected signature: ",
            sig,
            ". ",
            means,
            ". Difference (",
            chat_state$level2,
            " - ",
            chat_state$level1,
            ") = ",
            sprintf("%.3f", row$diff),
            "; p = ",
            .fmt_p(row$pvalue),
            ", padj = ",
            .fmt_p(row$padj),
            "."
          )
        },
        name = "describe_signature",
        description = paste(
          "Summary of the currently selected signature: its mean score in each",
          "group, the between-group difference, and its p / adjusted-p."
        )
      ),
      ellmer::tool(
        function() {
          sig <- chat_state$selected_sig
          if (is.null(sig)) {
            return("No signature is selected yet.")
          }
          genes <- intersect(
            chat_state$dataset$signatures[[sig]],
            rownames(chat_state$expr)
          )
          cm <- chat_state$contrast_meta
          if (length(genes) == 0 || is.null(cm)) {
            return("No member genes / contrast available for this signature.")
          }
          le_expr <- chat_state$expr[, cm$sample, drop = FALSE]
          le <- signature_leading_edge(
            le_expr,
            genes,
            cm[[chat_state$group_col]],
            chat_state$level1,
            chat_state$level2
          )
          if (nrow(le) == 0) {
            return("No leading-edge genes for this signature.")
          }
          top <- utils::head(le, 12)
          paste0(
            sig,
            " has ",
            length(genes),
            " member genes in the expression matrix. ",
            "Top leading-edge genes by |difference| (",
            chat_state$level2,
            " - ",
            chat_state$level1,
            "): ",
            paste(sprintf("%s (Δ %.2f)", top$gene, top$diff), collapse = "; "),
            "."
          )
        },
        name = "describe_leading_edge",
        description = paste(
          "Leading-edge summary for the selected signature: how many member",
          "genes are present and the genes with the largest between-group",
          "expression difference (its leading edge)."
        )
      ),
      # --- Control tools: drive the app's inputs (updateXxxInput / DT proxy are
      # all safe to call mid-stream, outside a reactive context).
      ellmer::tool(
        function(method) {
          if (!method %in% names(method_labels)) {
            return(paste0(
              "Unknown method. Choose one of: ",
              toString(names(method_labels))
            ))
          }
          updateRadioButtons(session, "method", selected = method)
          paste0("Scoring method switched to ", method_labels[[method]], ".")
        },
        name = "set_method",
        description = paste(
          "Change the scoring method (re-scores every signature). ssgsea =",
          "single-sample GSEA; singscore = rank-based; zscore = module z-score;",
          "mean = mean expression of the set."
        ),
        arguments = list(
          method = ellmer::type_enum(
            names(method_labels),
            description = "The scoring method id."
          )
        )
      ),
      ellmer::tool(
        function(group_by = NULL, reference = NULL, compared_with = NULL) {
          meta <- chat_state$dataset$metadata
          cols <- setdiff(names(meta), "sample")
          # Changing the grouping variable resets its two levels to defaults, so
          # honour group_by alone; adjust levels only within the current group.
          if (!is.null(group_by)) {
            if (!group_by %in% cols) {
              return(paste0(
                "Unknown grouping column. Available: ",
                toString(cols)
              ))
            }
            updateSelectInput(session, "group_col", selected = group_by)
            return(paste0(
              "Grouping variable switched to ",
              group_by,
              "; the two contrast levels reset to that variable's defaults. Call",
              " set_contrast again with reference / compared_with to pick levels."
            ))
          }
          levs <- sort(unique(stats::na.omit(as.character(
            meta[[chat_state$group_col]]
          ))))
          changed <- character(0)
          if (!is.null(reference)) {
            if (!reference %in% levs) {
              return(paste0(
                "Unknown reference level for ",
                chat_state$group_col,
                ". Levels: ",
                toString(levs)
              ))
            }
            updateSelectInput(session, "level1", selected = reference)
            changed <- c(changed, paste0("reference = ", reference))
          }
          if (!is.null(compared_with)) {
            if (!compared_with %in% levs) {
              return(paste0(
                "Unknown 'compared with' level for ",
                chat_state$group_col,
                ". Levels: ",
                toString(levs)
              ))
            }
            updateSelectInput(session, "level2", selected = compared_with)
            changed <- c(changed, paste0("compared with = ", compared_with))
          }
          if (length(changed) == 0) {
            return("No contrast changes given.")
          }
          paste0("Contrast updated: ", toString(changed), ".")
        },
        name = "set_contrast",
        description = paste(
          "Change the group contrast. group_by is a metadata column to group",
          "samples by (e.g. group, subtype, er_status, stage); reference and",
          "compared_with are the two levels of the CURRENT grouping to contrast",
          "(difference = compared_with - reference). Changing group_by resets",
          "the levels, so set it in one call and pick levels in a follow-up call.",
          "Any argument may be omitted."
        ),
        arguments = list(
          group_by = ellmer::type_string(
            "Metadata column to group samples by.",
            required = FALSE
          ),
          reference = ellmer::type_string(
            "Reference level of the current grouping.",
            required = FALSE
          ),
          compared_with = ellmer::type_string(
            "Level compared against the reference.",
            required = FALSE
          )
        )
      ),
      ellmer::tool(
        function(signature) {
          r <- chat_state$ranking
          if (is.null(r)) {
            return("No ranking is available yet.")
          }
          idx <- match(signature, r$signature)
          if (is.na(idx)) {
            return(paste0(
              "'",
              signature,
              "' is not among the ranked signatures."
            ))
          }
          DT::selectRows(DT::dataTableProxy("ranking"), idx)
          paste0(
            "Signature detail and Pathway genes now focus ",
            signature,
            "."
          )
        },
        name = "set_signature",
        description = paste(
          "Focus a signature in the Signature detail and Pathway genes views (by",
          "selecting its row in the ranking table). Use when the user asks to",
          "look at one specific Hallmark signature."
        ),
        arguments = list(
          signature = ellmer::type_string(
            "A Hallmark signature name from the current ranking."
          )
        )
      ),
      ellmer::tool(
        function(n) {
          n <- as.character(n)
          choices <- c("15", "25", "50")
          if (!n %in% choices) {
            return(paste0("n must be one of: ", toString(choices)))
          }
          updateSelectInput(session, "ntop", selected = n)
          paste0("Score heatmap now shows the top ", n, " signatures.")
        },
        name = "set_signature_count",
        description = paste(
          "Set how many top-ranked signatures the score heatmap shows: 15, 25,",
          "or 50."
        ),
        arguments = list(
          n = ellmer::type_string(
            "Number of signatures to show: 15, 25, or 50."
          )
        )
      ),
      ellmer::tool(
        function(p_threshold = NULL, max_labels = NULL) {
          changed <- character(0)
          if (!is.null(p_threshold)) {
            p_threshold <- max(0.001, min(0.1, p_threshold))
            updateSliderInput(session, "vp", value = p_threshold)
            changed <- c(changed, paste0("significance p < ", p_threshold))
          }
          if (!is.null(max_labels)) {
            max_labels <- as.integer(max(0, min(25, max_labels)))
            updateSliderInput(session, "vlabels", value = max_labels)
            changed <- c(changed, paste0("max labels = ", max_labels))
          }
          if (length(changed) == 0) {
            return("Nothing to change for the volcano.")
          }
          paste0("Volcano updated: ", toString(changed), ".")
        },
        name = "set_volcano",
        description = paste(
          "Change the signature volcano: p_threshold is the significance cutoff",
          "(0.001-0.1); max_labels is how many top signatures to label (0-25).",
          "Either may be omitted."
        ),
        arguments = list(
          p_threshold = ellmer::type_number(
            "Significance cutoff, 0.001 to 0.1.",
            required = FALSE
          ),
          max_labels = ellmer::type_integer(
            "Number of top signatures to label, 0 to 25.",
            required = FALSE
          )
        )
      )
    )
  }

  byok_chat_server(
    "chat",
    system_prompt = sig_system_prompt,
    tools = sig_tools
  )

  # --- Ranking table -------------------------------------------------------
  output$ranking <- DT::renderDT(
    {
      df <- ranking()
      dt <- DT::datatable(
        df,
        selection = "single",
        rownames = FALSE,
        class = "cell-border stripe hover",
        extensions = "Buttons",
        options = list(
          dom = "Bfrtip",
          buttons = list("copy", "csv"),
          pageLength = 15,
          order = list()
        )
      )
      dt <- DT::formatRound(
        dt,
        c(grep("^mean_", names(df), value = TRUE), "diff"),
        digits = 3
      )
      DT::formatSignif(dt, c("pvalue", "padj"), digits = 3)
    },
    server = TRUE
  )
  # The Ranking table sits on a hidden tab; keep it rendered so its row
  # selection (and the assistant's selectRows proxy) drive the detail views.
  outputOptions(output, "ranking", suspendWhenHidden = FALSE)

  # --- Overview: a volcano of every signature (effect vs significance) ------
  # Reuse the volcano module: map the ranking's contrast onto its gene/logFC/p
  # contract (colour by significance alone, so it works across scoring methods
  # whose effect scales differ). Drop unscored sets (NA).
  volcano_df <- reactive({
    r <- ranking()
    r <- r[!is.na(r$diff) & !is.na(r$padj), , drop = FALSE]
    data.frame(
      # Short, lower-case labels (drop the HALLMARK_ prefix) so the volcano's
      # point labels stay legible and repel cleanly instead of colliding.
      gene = tolower(gsub("_", " ", sub("^HALLMARK_", "", r$signature))),
      logFC = r$diff,
      padj = r$padj,
      stringsAsFactors = FALSE
    )
  })
  volcano_server(
    "volcano",
    de_results = volcano_df,
    lfc_threshold = reactive(0),
    p_threshold = reactive(input$vp),
    p_col = reactive("padj"),
    label_top_n = reactive(input$vlabels),
    xlab = reactive(sprintf(
      "score difference (%s - %s)",
      input$level2,
      input$level1
    ))
  )

  # Selected signature: the chosen ranking row, else the top-ranked one.
  selected_sig <- reactive({
    rows <- input$ranking_rows_selected
    if (length(rows) > 0) {
      ranking()$signature[rows[1]]
    } else {
      ranking()$signature[1]
    }
  })

  # --- Score heatmap: the most differential signatures x samples -----------
  heat_rows <- reactive(utils::head(
    ranking()$signature,
    as.integer(input$ntop)
  ))
  heatmap_server(
    "heat",
    matrix = contrast_scores,
    rows = heat_rows,
    metadata = contrast_meta,
    scale = reactive("row"),
    cluster_rows = reactive(TRUE),
    group_col = reactive(input$group_col),
    # Dozens of samples per group: individual column labels are illegible and
    # collide, so hide them (the group facet strips carry the context).
    show_samples = reactive(FALSE)
  )

  # --- Signature detail: the selected signature's scores by group ----------
  output$detail_sig_label <- renderUI({
    s <- selected_sig()
    if (is.null(s) || is.na(s)) {
      return(tags$p(
        class = "text-muted small mb-2",
        "Select a signature in the Ranking table."
      ))
    }
    tags$p(
      class = "mb-2",
      "Showing ",
      tags$strong(s),
      tags$span(
        class = "text-muted small",
        " - select another Ranking row to change."
      )
    )
  })
  group_comparison_server(
    "detail",
    values = reactive(contrast_scores()[selected_sig(), ]),
    metadata = contrast_meta,
    # The panel header names the signature; keep the axis title short so the
    # long HALLMARK_ name can't overrun the (rotated) y axis.
    value_label = reactive("signature score"),
    group_col = reactive(input$group_col)
  )

  # --- Pathway genes: the selected signature's member genes -----------------
  # Which genes drive the signature's score, on the raw expression scale.
  sig_genes <- reactive(
    intersect(signatures()[[selected_sig()]], rownames(expr()))
  )
  le_expr <- reactive(expr()[, contrast_meta()$sample, drop = FALSE])
  leading <- reactive({
    shiny::validate(shiny::need(
      length(sig_genes()) > 0,
      "No member genes of this signature are in the expression matrix."
    ))
    signature_leading_edge(
      le_expr(),
      sig_genes(),
      contrast_meta()[[input$group_col]],
      input$level1,
      input$level2
    )
  })

  output$le_title <- renderText(paste(selected_sig(), "- member genes"))
  # Heatmap the top leading-edge genes (by |diff|) so it stays readable even
  # for large sets; the table beside it lists them all.
  heatmap_server(
    "genes",
    matrix = le_expr,
    rows = reactive(utils::head(leading()$gene, 30)),
    metadata = contrast_meta,
    scale = reactive("row"),
    cluster_rows = reactive(TRUE),
    group_col = reactive(input$group_col),
    show_samples = reactive(FALSE)
  )
  output$leading_edge <- DT::renderDT(
    {
      df <- leading()
      dt <- DT::datatable(
        df,
        rownames = FALSE,
        selection = "none",
        class = "cell-border stripe hover",
        extensions = "Buttons",
        options = list(
          dom = "Bfrtip",
          buttons = list("copy", "csv"),
          pageLength = 15
        )
      )
      DT::formatRound(dt, setdiff(names(df), "gene"), digits = 3)
    },
    server = TRUE
  )

  # --- Keep the assistant's state mirror current --------------------------
  # Reads reactives in a reactive context and writes plain values into the env
  # the assistant tools read (see the tool definitions above). Reactives that
  # can validate/req-fail are read defensively so the mirror never errors.
  observe({
    ds <- dataset()
    chat_state$dataset <- ds
    chat_state$dataset_label <- names(datasets)[match(input$dataset, datasets)]
    chat_state$method <- input$method
    chat_state$method_label <- unname(
      method_labels[match(input$method %||% "ssgsea", names(method_labels))]
    )
    chat_state$group_col <- input$group_col %||% "group"
    gc <- make_group_choices(ds$metadata)
    chat_state$group_label <- names(gc)[match(input$group_col, gc)]
    chat_state$level1 <- input$level1
    chat_state$level2 <- input$level2
    chat_state$ntop <- input$ntop
    chat_state$vp <- input$vp
    chat_state$vlabels <- input$vlabels
    chat_state$expr <- signature_expression_matrix(ds)
    chat_state$ranking <- tryCatch(ranking(), error = function(e) NULL)
    chat_state$contrast_meta <- tryCatch(contrast_meta(), error = function(e) {
      NULL
    })
    chat_state$selected_sig <- tryCatch(
      selected_sig(),
      error = function(e) NULL
    )
  })
}

shinyApp(ui, server)
