# Genome Explorer -- classic Shiny (R). Explore recurrent breast-cancer somatic
# mutations in genomic context: an embedded igv.js browser alongside a variant
# table, navigable by driver gene and by variant, with a scoped BYOK assistant.
#
# App (L3) layer: page layout + wiring only. Compute lives in the logic layer
# (R/_shared, Shiny-free); UI in the component modules (R/_modules).
#
# Vendored copy. This directory is self-contained: it runs and deploys on its
# own, with its own modules and its own data. Upstream is
# posit-dev/lifescience-shiny-gallery, where R/_shared and R/_modules are
# generated by scripts/sync-shared.R and git-ignored; here they are checked in.
# Change them upstream and re-copy rather than editing them in place.
#
# Requires igvShiny, which comes from Bioconductor rather than CRAN; the
# assistant additionally needs ellmer + shinychat.
#
# No bslib: this app ships a bespoke, bslib-free UI (frontend-design; see
# www/app.css) - the simplest of the gallery apps: a top bar + a single-column
# browser workbench. The assistant is rebuilt bslib-free (byok_chat_ui_plain)
# reusing the byok-chat SERVER unchanged.

# Dev convenience: load a local, git-ignored .Renviron (e.g. BYOK API keys).
local({
  dir <- normalizePath(".", mustWork = FALSE)
  repeat {
    f <- file.path(dir, ".Renviron")
    if (file.exists(f)) {
      readRenviron(f)
      break
    }
    parent <- dirname(dir)
    if (identical(parent, dir)) {
      break
    }
    dir <- parent
  }
})

library(shiny)
library(DT)
library(igvShiny)

# Logic layer first (functions the modules call), then the component modules.
for (f in list.files("R/_shared", pattern = "[.][Rr]$", full.names = TRUE)) {
  source(f)
}
for (f in list.files("R/_modules", pattern = "[.][Rr]$", full.names = TRUE)) {
  source(f)
}

mutations <- read_mutations("data")
genes_by_recurrence <- names(sort(
  tapply(mutations$count, mutations$gene, sum),
  decreasing = TRUE
))
max_recurrence <- max(mutations$count)

# A locus string (chrom:start-end) spanning a gene's variants, so navigation
# uses explicit coordinates rather than relying on igv.js gene-name lookup.
gene_locus <- function(muts, gene, flank = 2000L) {
  g <- muts[muts$gene == gene, , drop = FALSE]
  if (nrow(g) == 0) {
    return(NULL)
  }
  sprintf("%s:%d-%d", g$chrom[1], min(g$pos) - flank, max(g$pos) + flank)
}

# --- Assistant summary helpers (app-local, Shiny-free) ----------------------
summarise_track <- function(muts, min_recur) {
  if (is.null(muts) || nrow(muts) == 0) {
    return("No mutations pass the current recurrence filter.")
  }
  by_gene <- sort(tapply(muts$count, muts$gene, sum), decreasing = TRUE)
  top <- utils::head(by_gene, 8L)
  paste0(
    "Mutation track (TCGA-BRCA somatic variants, hg19), recurrence filter >= ",
    min_recur,
    " tumors: ",
    nrow(muts),
    " distinct variants across ",
    length(by_gene),
    " genes. Most recurrently mutated genes (summed tumor counts): ",
    paste(sprintf("%s (%d)", names(top), as.integer(top)), collapse = ", "),
    "."
  )
}

summarise_gene_variants <- function(gv, gene) {
  if (is.null(gv) || nrow(gv) == 0) {
    return(paste0(
      "No variants for ",
      gene,
      " pass the current recurrence filter."
    ))
  }
  o <- gv[order(gv$count, decreasing = TRUE), , drop = FALSE]
  top <- utils::head(o, 8L)
  paste0(
    gene,
    ": ",
    nrow(gv),
    " variant(s) shown on ",
    top$chrom[1],
    ", by recurrence -- ",
    paste(
      sprintf(
        "%s at %s:%d (n=%d)",
        top$protein_change,
        top$chrom,
        top$pos,
        top$count
      ),
      collapse = "; "
    ),
    "."
  )
}

# --- Assistant UI, rebuilt without bslib -----------------------------------
byok_chat_ui_plain <- function(
  id,
  title,
  subtitle = NULL,
  providers = c("gemini", "openai", "anthropic"),
  starters = NULL,
  placeholder = "Ask me anything...",
  height = "100%"
) {
  ns <- NS(id)
  providers <- .byok_chat_providers(providers)
  if (!.byok_chat_packages_ok() || length(providers) == 0) {
    return(tagList(
      div(
        class = "drawer-head",
        div(h2(title)),
        tags$button(
          class = "drawer-close",
          onclick = "GX.closeDrawer('assistant_drawer')",
          HTML("&times;")
        )
      ),
      div(
        class = "drawer-body",
        tags$p(
          "The AI assistant is off because its packages (ellmer, shinychat)",
          "are not installed."
        )
      )
    ))
  }
  choices <- .byok_chat_provider_choices(providers)
  greeting <- if (
    nzchar(.byok_chat_env_first(.byok_chat_provider_meta(providers[1])$env))
  ) {
    paste(
      "Hi! A key was found in your environment - open **Model & key** below,",
      "pick a model, and click **Connect** to start chatting."
    )
  } else {
    paste(
      "Hi! Open **Model & key** below, paste an API key, and click",
      "**Connect** to start chatting."
    )
  }
  if (length(starters) > 0) {
    cards <- paste0(
      "- <span class=\"suggestion submit\">",
      vapply(unname(starters), htmltools::htmlEscape, character(1)),
      "</span>"
    )
    greeting <- paste0(greeting, "\n\n", paste(cards, collapse = "\n"))
  }
  tagList(
    tags$style(HTML(paste0(
      "#",
      ns("chat"),
      " .shiny-tool-request,#",
      ns("chat"),
      " .shiny-tool-result{display:none !important;}"
    ))),
    div(
      class = "drawer-head",
      div(h2(title), if (!is.null(subtitle)) div(class = "sub", subtitle)),
      div(
        style = "display:flex;align-items:center;gap:0.6rem;",
        uiOutput(ns("conn_badge"), inline = TRUE),
        tags$button(
          class = "drawer-close",
          onclick = "GX.closeDrawer('assistant_drawer')",
          HTML("&times;")
        )
      )
    ),
    tags$details(
      class = "byok",
      tags$summary(icon("gear"), " Model & key"),
      div(
        class = "byok-body",
        selectInput(
          ns("provider"),
          "Provider",
          choices = choices,
          selected = unname(choices)[1]
        ),
        uiOutput(ns("key_help")),
        passwordInput(
          ns("api_key"),
          "API key",
          placeholder = "Paste your key (kept in this session only)"
        ),
        selectizeInput(
          ns("model"),
          "Model",
          choices = character(0),
          selected = character(0),
          multiple = FALSE,
          options = list(
            create = TRUE,
            placeholder = "Provider default - pick or type a model"
          )
        ),
        actionButton(
          ns("refresh_models"),
          "List models for this key",
          class = "btn-line"
        ),
        uiOutput(ns("model_source")),
        div(
          style = "display:flex;gap:0.5rem;margin:0.6rem 0;",
          actionButton(ns("connect"), "Connect", class = "btn-line btn-fill"),
          actionButton(ns("forget"), "Forget key", class = "btn-line")
        ),
        uiOutput(ns("cred_status"))
      )
    ),
    div(
      class = "drawer-body chat",
      shinychat::chat_ui(
        ns("chat"),
        height = height,
        placeholder = placeholder,
        greeting = greeting
      )
    )
  )
}

# Client-side glue: top-bar page nav (plain show/hide + resize dispatch) and a
# slide-in assistant drawer + scrim.
GX_JS <- paste0(
  "window.GX={",
  "_scrim:function(){return document.getElementById('scrim');},",
  "openDrawer:function(id){var d=document.getElementById(id);",
  "if(d){d.classList.add('open');GX._scrim().classList.add('show');}},",
  "closeDrawer:function(id){var d=document.getElementById(id);",
  "if(d){d.classList.remove('open');}GX._sync();},",
  "toggleDrawer:function(id){var d=document.getElementById(id);",
  "if(d&&d.classList.contains('open'))GX.closeDrawer(id);else GX.openDrawer(id);},",
  "closeAll:function(){document.querySelectorAll('.drawer.open').forEach(",
  "function(d){d.classList.remove('open');});GX._sync();},",
  "_sync:function(){if(!document.querySelector('.drawer.open'))",
  "GX._scrim().classList.remove('show');},",
  "_resize:function(){setTimeout(function(){",
  "window.dispatchEvent(new Event('resize'));},60);},",
  "nav:function(name){document.querySelectorAll('.topnav .navlink[data-page]')",
  ".forEach(function(a){a.classList.toggle('active',",
  "a.getAttribute('data-page')===name);});",
  "document.querySelectorAll('.page-section[data-page]').forEach(function(s){",
  "s.style.display=(s.getAttribute('data-page')===name)?'block':'none';});",
  "GX._resize();window.scrollTo({top:0,behavior:'smooth'});},",
  # Demo runs on the Browser view (where the tour targets live); reset there,
  # then fire the `demo` input once the DOM has settled.
  "startDemo:function(){GX.closeAll();GX.nav('Browser');",
  "setTimeout(function(){if(window.Shiny&&Shiny.setInputValue)",
  "Shiny.setInputValue('demo',Date.now(),{priority:'event'});},420);}",
  "};"
)

# Collapsible per-panel guidance (native <details>, no JS).
card_help <- function(...) {
  tags$details(
    class = "help",
    tags$summary("How to read this"),
    div(class = "body", ...)
  )
}

# A designed section (bslib-free "card"): eyebrow + title head, then body.
gx_panel <- function(id, eyebrow, title, ..., class = NULL) {
  div(
    class = paste("panel", class),
    id = id,
    div(
      class = "panel-head",
      div(class = "eyebrow", eyebrow),
      h3(class = "panel-title", title)
    ),
    div(class = "panel-body", ...)
  )
}

# --- Browser view: context + controls header, then browser + table --------
browser_page <- tagList(
  div(
    class = "gx-head",
    div(
      class = "gx-context",
      id = "hdr-dataset",
      div(class = "eyebrow", "Genome browser · hg19"),
      h1(
        class = "gx-head-title",
        "Recurrent driver mutations in genomic context"
      ),
      tags$p(
        class = "gx-lede",
        "Somatic mutations recurrently found across TCGA breast tumours, placed",
        "on the hg19 reference genome. Pick a driver gene or raise the",
        "recurrence filter; click a variant in the table to zoom the browser to",
        "it."
      ),
      uiOutput("gx_stats")
    ),
    div(
      class = "gx-controls",
      id = "hdr-controls",
      div(class = "eyebrow", "Controls"),
      selectInput("focus_gene", "Focus gene", choices = genes_by_recurrence),
      sliderInput(
        "min_recur",
        "Min recurrence (tumors)",
        min = 2,
        max = max_recurrence,
        value = 2,
        step = 1
      )
    )
  ),
  gx_panel(
    "hdr-browser",
    "Genome browser",
    "Genomic context - igv.js (hg19)",
    class = "hero",
    card_help(
      "The IGV browser shows the mutation track over the reference genome. Drag",
      "to pan and scroll to zoom; the focus-gene control and the variant table",
      "both drive where it navigates. Feature labels read as gene / protein",
      "change / recurrence."
    ),
    genome_browser_ui("gb")
  ),
  gx_panel(
    "hdr-table",
    "Variant table",
    textOutput("variants_header", inline = TRUE),
    card_help(
      "Every variant for the focused gene at the current recurrence filter.",
      "Click a row to zoom the browser to that mutation; sort by recurrence to",
      "surface the most frequent hotspots."
    ),
    DT::DTOutput("variants")
  )
)

# --- About view ------------------------------------------------------------
about_page <- div(
  class = "about",
  markdown(
    "## Genome Explorer

Explore recurrent breast-cancer somatic mutations in genomic context: an
embedded **igv.js** browser alongside a variant table, navigable by driver gene
and by variant. Part of the **Lifescience Shiny Gallery**: reusable Shiny apps
and components for common bioinformatics workflows.

#### What you can do
- **Genome browser** - see the mutation track over the hg19 reference; pan and
  zoom with full IGV interactivity.
- **Focus gene** - jump the browser to a driver gene's locus.
- **Variant table** - browse every variant for the focused gene; click a row to
  zoom to that mutation.
- **Recurrence filter** - keep only variants recurrent in at least *N* tumors;
  it drives both the browser track and the table.
- **Assistant** - a scoped, bring-your-own-key chat that can summarise the
  track, describe the visible variants, and drive navigation for you.

#### Getting started
In the **Browser** view, pick a driver gene in the controls to navigate the
browser, then click rows in the variant table to zoom to individual mutations.
Raise the recurrence filter to focus on the most frequent hotspots. Open the
**Assistant** from the top bar to ask about the track or have it drive the view.

### Data
Recurrent somatic mutations from the **TCGA breast-invasive-carcinoma
(TCGA-BRCA)** cohort, one row per distinct variant with the number of tumors
carrying it. Coordinates are **GRCh37 / hg19**, matching the reference genome
the browser loads. A curated, recurrent subset ships with the app for a fast,
reproducible demo. Prep scripts under `data/prep/` are the source of truth
(provenance + licensing).

#### Citations
- TCGA Network. *Comprehensive molecular portraits of human breast tumours.*
  Nature 490:61–70 (2012). doi:10.1038/nature11412
- Robinson JT, et al. *Integrative Genomics Viewer.* Nat Biotechnol 29:24–26
  (2011). doi:10.1038/nbt.1754

TCGA data are subject to the [NIH Genomic Data Sharing Policy](https://gdc.cancer.gov/access-data/data-access-policies);
the recurrent subset here is derived from open-access summaries.

### The assistant
The **Assistant** (top bar) opens a bring-your-own-key chat (Google Gemini,
OpenAI, or Anthropic). Your key is held only in the session's server memory and
is never written to disk. The assistant is scoped to this app: it can summarise
the mutation track, describe the variants currently shown, and drive the browser
(navigate to a gene or locus, change the recurrence filter). It declines
off-topic questions.

### Credits
Built with **Shiny**, embedding **igv.js** via the **igvShiny** package. MIT ©
2026 Posit Software, PBC. Authored by Samuel Bharti."
  )
)

ui <- tagList(
  tags$head(
    tags$meta(
      name = "viewport",
      content = "width=device-width, initial-scale=1"
    ),
    tags$title("Genome Explorer"),
    tags$link(rel = "preconnect", href = "https://fonts.googleapis.com"),
    tags$link(
      rel = "preconnect",
      href = "https://fonts.gstatic.com",
      crossorigin = NA
    ),
    tags$link(
      rel = "stylesheet",
      href = paste0(
        "https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@400;",
        "500;600;700&family=JetBrains+Mono:wght@400;500&display=swap"
      )
    ),
    tags$link(
      rel = "stylesheet",
      href = paste0("app.css?v=", as.integer(file.info("www/app.css")$mtime))
    ),
    # shinychat's version gate reads window.bootstrap.Tab.VERSION; load Bootstrap
    # 5's JS bundle (a plain CDN script, not bslib) so the gate is satisfied.
    tags$script(
      src = paste0(
        "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/",
        "bootstrap.bundle.min.js"
      )
    ),
    tags$script(HTML(GX_JS))
  ),
  cicerone::use_cicerone(),
  # Top bar: wordmark + page nav (Browser / About) + utilities.
  div(
    class = "topbar",
    div(
      class = "brand",
      div(class = "mark", icon("dna")),
      "Genome Explorer",
      tags$small("hg19 · TCGA-BRCA")
    ),
    div(
      class = "topnav",
      tags$a(
        class = "navlink active",
        `data-page` = "Browser",
        onclick = "GX.nav('Browser')",
        icon("dna"),
        "Browser"
      ),
      tags$a(
        class = "navlink",
        `data-page` = "About",
        onclick = "GX.nav('About')",
        icon("circle-info"),
        "About"
      ),
      tags$a(
        class = "navlink",
        id = "open_assistant",
        onclick = "GX.toggleDrawer('assistant_drawer')",
        icon("robot"),
        "Assistant"
      ),
      tags$a(
        class = "navlink",
        onclick = "GX.startDemo()",
        icon("circle-play"),
        "Demo"
      ),
      tags$a(
        class = "navlink",
        href = "https://github.com/posit-dev/lifescience-shiny-gallery",
        target = "_blank",
        rel = "noopener",
        icon("github"),
        "Source"
      )
    )
  ),
  div(
    class = "page",
    div(
      class = "page-section",
      `data-page` = "Browser",
      style = "display:block;",
      browser_page
    ),
    div(
      class = "page-section",
      `data-page` = "About",
      style = "display:none;",
      about_page
    )
  ),
  div(
    class = "footer",
    "Genome Explorer · MIT © 2026 Posit Software, PBC · Authored by Samuel Bharti"
  ),
  # Page-level overlays: scrim + the assistant drawer.
  div(id = "scrim", class = "scrim", onclick = "GX.closeAll()"),
  div(
    class = "drawer",
    id = "assistant_drawer",
    byok_chat_ui_plain(
      "chat",
      title = "Genome Explorer assistant",
      subtitle = "Bring your own Gemini / OpenAI / Anthropic key.",
      placeholder = "Ask about the track, a gene, or a variant...",
      starters = c(
        "Summarise the mutation track and its most recurrent genes.",
        "What variants are shown for the current gene?",
        "Navigate to TP53.",
        "Show only mutations recurrent in at least 5 tumors.",
        "Explain the PIK3CA H1047R hotspot mutation.",
        "Which gene is mutated in the most tumors?"
      )
    )
  )
)

server <- function(input, output, session) {
  # --- Guided demo tour (the "Demo" item in the top bar) ------------------
  demo_guide <- cicerone::Cicerone$new(overlay_click_next = TRUE)$step(
    "hdr-controls",
    "1. Set the view",
    paste(
      "Start here: pick a driver gene to jump the browser to its locus, and",
      "set the minimum recurrence. Both drive the browser track and the table."
    )
  )$step(
    "hdr-dataset",
    "About this dataset",
    "A quick summary of the loaded cohort: TCGA-BRCA somatic mutations on hg19, with live variant and gene counts at the current filter."
  )$step(
    "hdr-browser",
    "Genome browser",
    "The embedded igv.js browser shows the mutation track over the reference genome. Drag to pan and scroll to zoom."
  )$step(
    "hdr-table",
    "Variant table",
    "Every variant for the focused gene at the current recurrence filter. Click a row to zoom the browser to that mutation."
  )$step(
    "open_assistant",
    "AI assistant",
    "Open the assistant (bring your own API key) to summarise the track, describe visible variants, or drive navigation for you."
  )$step(
    ".topnav .navlink[data-page='About']",
    "Learn more",
    "Finally, the About page has full data provenance, methods, and citations. That's the tour!",
    is_id = FALSE
  )
  observeEvent(input$demo, demo_guide$init()$start())

  # A plain (non-reactive) mirror of the app's current state, read by the
  # assistant's tools (kept current by the observer at the end of server()).
  chat_state <- new.env(parent = emptyenv())

  filtered <- reactive({
    mutations[mutations$count >= input$min_recur, , drop = FALSE]
  })
  gene_variants <- reactive({
    f <- filtered()
    f[f$gene == input$focus_gene, , drop = FALSE]
  })

  # At-a-glance dataset stats (live at the current recurrence filter).
  output$gx_stats <- renderUI({
    f <- filtered()
    ng <- length(unique(f$gene))
    top <- if (nrow(f) > 0) {
      names(sort(tapply(f$count, f$gene, sum), decreasing = TRUE))[1]
    } else {
      "-"
    }
    stat <- function(k, v) {
      div(class = "gx-stat", div(class = "k", k), div(class = "v", v))
    }
    div(
      class = "gx-stats",
      stat("Variants", nrow(f)),
      stat("Genes", ng),
      stat("Top gene", top)
    )
  })

  # Where the browser navigates: the focused gene's locus, a clicked variant, or
  # a coordinate range the assistant sets. Defined before the tools use it.
  locus <- reactiveVal(NULL)

  # --- Assistant: scoped, tool-using BYOK chat ----------------------------
  genome_system_prompt <- paste(
    "You are the Genome Explorer assistant, embedded in an app that shows",
    "recurrent somatic mutations from the TCGA-BRCA breast-cancer cohort in an",
    "igv.js genome browser (hg19) alongside a variant table. Your ONLY job is to",
    "help the user explore and interpret THIS app: its mutation track, the",
    "variants shown for the focused gene, and the current genomic locus.",
    "",
    "Before answering about the data, call the matching read tool for its live",
    "state: track_summary (the whole track), visible_mutations (the focused",
    "gene's variants), current_locus (where the browser is pointed). Never invent",
    "gene names, protein changes, positions, or recurrence counts -- quote the",
    "tool output. Explain protein changes (e.g. PIK3CA H1047R), recurrence, and",
    "genomic loci plainly.",
    "",
    "You can also DRIVE the browser when the user asks -- then briefly say what",
    "you changed:",
    "- navigate_to_gene: focus a driver gene (jumps the browser to its locus and",
    "  filters the variant table to it).",
    "- navigate_to_locus: navigate to an explicit chrom:start-end region.",
    "- set_recurrence_filter: keep only variants recurrent in at least N tumors",
    "  (drives the track and the table together).",
    "After changing a control, you may re-read the relevant view to interpret it.",
    "",
    "Refuse anything outside Genome Explorer and this dataset: for off-topic or",
    "general questions, briefly decline and point back to what the app can do.",
    "Be concise.",
    sep = "\n"
  )

  genome_tools <- list()
  if (requireNamespace("ellmer", quietly = TRUE)) {
    genome_tools <- list(
      ellmer::tool(
        function() {
          summarise_track(chat_state$filtered, chat_state$min_recur)
        },
        name = "track_summary",
        description = paste(
          "Summary of the whole mutation track at the current recurrence filter:",
          "variant and gene counts, and the most recurrently mutated genes."
        )
      ),
      ellmer::tool(
        function() {
          summarise_gene_variants(
            chat_state$gene_variants,
            chat_state$focus_gene
          )
        },
        name = "visible_mutations",
        description = paste(
          "Summary of the variants currently shown for the focused gene: how",
          "many, and each one's protein change, position, and recurrence count."
        )
      ),
      ellmer::tool(
        function() {
          loc <- chat_state$locus
          if (is.null(loc) || !nzchar(loc)) {
            return(paste0(
              "The browser is focused on ",
              chat_state$focus_gene,
              " (no explicit region set)."
            ))
          }
          paste0(
            "The browser is navigated to ",
            loc,
            " (hg19), currently focusing ",
            chat_state$focus_gene,
            "."
          )
        },
        name = "current_locus",
        description = paste(
          "The genomic region (chrom:start-end, hg19) the browser is currently",
          "navigated to, and the focused gene."
        )
      ),
      # --- Control tools: drive navigation and the recurrence filter. ---------
      ellmer::tool(
        function(gene) {
          if (!gene %in% genes_by_recurrence) {
            return(paste0(
              "Unknown gene. This dataset covers: ",
              toString(genes_by_recurrence)
            ))
          }
          updateSelectInput(session, "focus_gene", selected = gene)
          paste0(
            "Focused ",
            gene,
            "; the browser is navigating to its locus and the table now shows",
            " its variants."
          )
        },
        name = "navigate_to_gene",
        description = paste(
          "Focus a driver gene: jumps the igv.js browser to the gene's locus and",
          "filters the variant table to it. Use when the user names a gene to",
          "look at."
        ),
        arguments = list(
          gene = ellmer::type_enum(
            genes_by_recurrence,
            description = "The driver gene to focus."
          )
        )
      ),
      ellmer::tool(
        function(region) {
          region <- trimws(region %||% "")
          if (!grepl("^[A-Za-z0-9_]+:[0-9,]+-[0-9,]+$", region)) {
            return(paste0(
              "Region must look like chrom:start-end, e.g. chr3:178935000-",
              "178938000. Got: ",
              region
            ))
          }
          locus(region)
          paste0("Browser navigating to ", region, ".")
        },
        name = "navigate_to_locus",
        description = paste(
          "Navigate the browser to an explicit genomic region in hg19,",
          "formatted chrom:start-end (e.g. chr17:7571720-7590868). Use when the",
          "user gives coordinates rather than a gene."
        ),
        arguments = list(
          region = ellmer::type_string(
            "A genomic region as chrom:start-end (hg19)."
          )
        )
      ),
      ellmer::tool(
        function(min_tumors) {
          min_tumors <- as.integer(max(2, min(max_recurrence, min_tumors)))
          updateSliderInput(session, "min_recur", value = min_tumors)
          paste0(
            "Recurrence filter set to >= ",
            min_tumors,
            " tumors (applies to the track and the table)."
          )
        },
        name = "set_recurrence_filter",
        description = paste0(
          "Keep only variants recurrent in at least this many tumors (2 to ",
          max_recurrence,
          "). Drives both the browser track and the variant table."
        ),
        arguments = list(
          min_tumors = ellmer::type_integer(
            paste0("Minimum recurrence, 2 to ", max_recurrence, ".")
          )
        )
      )
    )
  }

  byok_chat_server(
    "chat",
    system_prompt = genome_system_prompt,
    tools = genome_tools
  )

  # --- Variant table: variants for the focused gene ------------------------
  output$variants_header <- renderText({
    sprintf("%s - %d variants", input$focus_gene, nrow(gene_variants()))
  })
  output$variants <- DT::renderDT(
    {
      DT::datatable(
        gene_variants()[, c("gene", "protein_change", "chrom", "pos", "count")],
        selection = "single",
        rownames = FALSE,
        class = "cell-border stripe hover",
        extensions = "Buttons",
        options = list(
          dom = "Bfrtip",
          buttons = list("copy", "csv"),
          pageLength = 8,
          order = list(list(4, "desc"))
        )
      )
    },
    server = TRUE
  )

  # Navigation: the focused gene's locus, or a clicked variant. (The assistant's
  # navigate_to_locus tool also writes locus directly.)
  observeEvent(input$focus_gene, locus(gene_locus(mutations, input$focus_gene)))
  observeEvent(input$variants_rows_selected, {
    gv <- gene_variants()
    row <- input$variants_rows_selected
    req(length(row) == 1, row >= 1, row <= nrow(gv))
    v <- gv[row, ]
    locus(sprintf("%s:%d-%d", v$chrom, v$pos - 60L, v$pos + 60L))
  })

  genome_browser_server("gb", mutations = filtered, locus = locus)

  # --- Keep the assistant's state mirror current --------------------------
  observe({
    chat_state$focus_gene <- input$focus_gene
    chat_state$min_recur <- input$min_recur
    chat_state$filtered <- filtered()
    chat_state$gene_variants <- gene_variants()
    chat_state$locus <- locus()
  })
}

shinyApp(ui, server)
