# DE Explorer (classic Shiny) -- composition of the reusable component modules
# over one shared DE dataset and one shared gene selection.
#
# This is the app (L3) layer: page layout + wiring only. All compute lives in
# the logic layer (R/_shared, Shiny-free) and all UI in the component modules
# (R/_modules).
#
# Vendored copy. This directory is self-contained: it runs and deploys on its
# own, with its own modules and its own data. Upstream is
# posit-dev/lifescience-shiny-gallery, where R/_shared and R/_modules are
# generated by scripts/sync-shared.R and git-ignored; here they are checked in.
# Change them upstream and re-copy rather than editing them in place.

# Dev convenience: load a local, git-ignored .Renviron (e.g. BYOK API keys) from
# the app dir or any parent up to the repo root, so Sys.getenv() sees them when
# the app is launched from its own working directory. A no-op when absent -- the
# deployed bundle has none; on the gallery, set env vars in the deploy config.
local({
  dir <- normalizePath(".", mustWork = FALSE)
  repeat {
    f <- file.path(dir, ".Renviron")
    if (file.exists(f)) {
      readRenviron(f)
      break
    }
    parent <- dirname(dir)
    if (identical(parent, dir)) {
      break
    }
    dir <- parent
  }
})

library(shiny)
library(bslib)
library(ggplot2)
library(DT)

# Logic layer first (functions the modules call), then the component modules.
for (f in list.files("R/_shared", pattern = "[.][Rr]$", full.names = TRUE)) {
  source(f)
}
for (f in list.files("R/_modules", pattern = "[.][Rr]$", full.names = TRUE)) {
  source(f)
}

# Bundled datasets (each a de_dataset contract dir). Labels shown in the picker;
# the real breast-cancer cohort leads as the showcase default.
datasets <- c(
  "Lung - TCGA LUAD vs LUSC (+ normal)" = "de-lung",
  "Breast cancer - TCGA-BRCA (tumor vs normal)" = "de-brca",
  "Airway - dexamethasone, DESeq2" = "de-airway",
  "Synthetic (reproducible)" = "de-synthetic",
  "Upload your own…" = "__upload__"
)

# Descriptive metadata per bundled dataset, for the "About this dataset" card:
# disease/design, public source, a portal link, the primary reference + DOI, and
# licensing. Keyed by the dataset dir; uploads fall back to a generic summary.
# Full provenance lives on the About page.
dataset_info <- list(
  "de-brca" = list(
    title = "TCGA-BRCA - breast invasive carcinoma",
    design = "Primary breast tumour vs solid-tissue normal (bulk RNA-seq)",
    source = "recount3 (uniformly reprocessed TCGA RNA-seq) → DESeq2 → VST",
    portal = "https://portal.gdc.cancer.gov/projects/TCGA-BRCA",
    portal_label = "GDC Data Portal - TCGA-BRCA",
    reference = "TCGA Network, Nature 490:61–70 (2012)",
    doi = "https://doi.org/10.1038/nature11412",
    license = "NIH GDS open-access (derived from recount3 summaries)"
  ),
  "de-lung" = list(
    title = "TCGA Lung - LUAD vs LUSC (+ normal)",
    design = paste(
      "Lung adenocarcinoma (LUAD) vs squamous-cell carcinoma (LUSC), with",
      "solid-tissue normal - three groups (bulk RNA-seq). DE contrast: LUAD",
      "vs LUSC; colour PCA / boxplots by group to see all three."
    ),
    source = paste(
      "recount3 (uniformly reprocessed TCGA-LUAD + TCGA-LUSC RNA-seq)",
      "→ DESeq2 → VST"
    ),
    portal = "https://portal.gdc.cancer.gov/projects/TCGA-LUAD",
    portal_label = "GDC Data Portal - TCGA-LUAD / LUSC",
    reference = paste(
      "TCGA Network, Nature 511:543–550 (2014, LUAD);",
      "Nature 489:519–525 (2012, LUSC)"
    ),
    doi = "https://doi.org/10.1038/nature13385",
    license = "NIH GDS open-access (derived from recount3 summaries)"
  ),
  "de-airway" = list(
    title = "Airway - dexamethasone-treated smooth muscle",
    design = "Airway smooth-muscle cells ± dexamethasone (in vitro, 4 donors)",
    source = "GEO GSE52778 (Himes et al.)",
    portal = "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE52778",
    portal_label = "GEO - GSE52778",
    reference = "Himes BE et al., PLoS One 9:e99625 (2014)",
    doi = "https://doi.org/10.1371/journal.pone.0099625",
    license = "Public (NCBI GEO)"
  ),
  "de-synthetic" = list(
    title = "Synthetic (reproducible)",
    design = "Simulated two-group differential expression",
    source = "Seeded generator in data/prep - a reproducible testing fixture",
    portal = NULL,
    portal_label = NULL,
    reference = "Not applicable (synthetic fixture)",
    doi = NULL,
    license = "MIT (this repository)"
  )
)

# DE contract files, for the "upload your own" path.
de_upload_files <- c(
  de_results = "de_results.csv",
  expression = "expression.csv",
  metadata = "metadata.csv"
)

# How many top-significant genes to seed the heatmap with when the user hasn't
# selected any rows in the table yet.
default_heatmap_n <- 15

# MSigDB Hallmark gene sets (symbols) for pathway enrichment of the DE hits.
.hallmark <- utils::read.csv("data/hallmark.csv", stringsAsFactors = FALSE)
hallmark_sets <- split(.hallmark$gene, .hallmark$signature)

# Collapsible per-card guidance: a small muted toggle that expands help inline.
# Uses a native <details> element, so it needs no JS and costs no layout space
# when collapsed (the default).
card_help <- function(...) {
  tags$details(
    class = "small text-body-secondary mb-2",
    tags$summary(
      class = "text-primary",
      style = "cursor: pointer;",
      "How to read this"
    ),
    div(class = "pt-2", ...)
  )
}

# --- Bring-your-own-data drawer --------------------------------------------
# Uploads live in a right-side offcanvas rather than inline in the controls, so
# the file pickers get room and a clear column spec. The drawer stays mounted
# (offcanvas only toggles visibility), so a validated upload isn't lost when it
# is closed. Selecting "Upload your own…" opens it (via the hidden trigger the
# server clicks); the visible controls button reopens it to change files.
de_upload_offcanvas <- div(
  class = "offcanvas offcanvas-start",
  tabindex = "-1",
  id = "de-upload-canvas",
  `aria-labelledby` = "de-upload-canvas-label",
  style = "width: 460px;",
  div(
    class = "offcanvas-header",
    tags$h5(
      class = "offcanvas-title",
      id = "de-upload-canvas-label",
      "Upload your own DE dataset"
    ),
    tags$button(
      type = "button",
      class = "btn-close",
      `data-bs-dismiss` = "offcanvas",
      `aria-label` = "Close"
    )
  ),
  div(
    class = "offcanvas-body",
    div(
      class = "small",
      tags$p(
        "Provide three CSV files matching the DE data contract. Column names",
        "must match exactly (case-sensitive) - the dataset is rejected",
        "otherwise, with the reason shown below."
      ),
      tags$ul(
        class = "mb-2 ps-3",
        tags$li(
          tags$code("de_results.csv"),
          " - one row per gene. Required columns: ",
          tags$code(toString(de_results_required)),
          "."
        ),
        tags$li(
          tags$code("expression.csv"),
          " - a ",
          tags$code("gene"),
          " column plus one numeric column per sample (log2-normalised)."
        ),
        tags$li(
          tags$code("metadata.csv"),
          " - one row per sample. Required columns: ",
          tags$code(toString(de_metadata_required)),
          "."
        )
      ),
      tags$p(
        class = "text-body-secondary",
        "Expression sample columns must match the metadata sample values, and",
        "every gene in de_results must appear in the expression matrix."
      )
    ),
    tags$hr(),
    data_upload_validate_ui("de_upload", de_upload_files)
  )
)

# Hidden trigger the server "clicks" to open the drawer when the dataset select
# switches to "Upload your own…", plus a hidden→revert bridge: when the drawer
# is closed with no valid upload, tell the server so it can restore the previous
# dataset instead of leaving the app on an empty "__upload__" selection.
de_upload_glue <- tagList(
  tags$button(
    id = "de-upload-trigger",
    class = "d-none",
    type = "button",
    `data-bs-toggle` = "offcanvas",
    `data-bs-target` = "#de-upload-canvas"
  ),
  tags$script(HTML(paste0(
    "Shiny.addCustomMessageHandler('open_de_upload', function(x){",
    "var b=document.getElementById('de-upload-trigger');",
    "if(b){b.click();}});",
    "document.addEventListener('DOMContentLoaded', function(){",
    "var el=document.getElementById('de-upload-canvas');",
    "if(el){el.addEventListener('hidden.bs.offcanvas', function(){",
    "Shiny.setInputValue('de_upload_closed', Date.now());});}});"
  )))
)

# --- Explorer page: the interactive tool -----------------------------------
# Three columns: global controls in the left rail (2), the analysis plots
# stacked in the middle (6), and the Assistant chat panel on the right (4). The
# chat's own key/model controls live in its offcanvas "Model & key" drawer. The
# control and chat rails are sticky so they stay in view while the plots scroll.
explorer_page <- tagList(
  cicerone::use_cicerone(),
  de_upload_offcanvas,
  de_upload_glue,
  fluidRow(
    column(
      width = 2,
      div(
        class = "position-sticky",
        style = "top: 1rem;",
        # Compact the controls: tighter padding + gaps, and force every input to the
        # full column width so nothing sits in a narrow default-width box.
        tags$style(HTML(paste0(
          ".de-controls .card-body{padding:0.75rem !important;}",
          ".de-controls .form-group,",
          ".de-controls .shiny-input-container",
          "{margin-bottom:0.5rem !important;width:100% !important;}",
          ".de-controls .control-label{margin-bottom:2px !important;}",
          ".de-controls hr{margin:0.5rem 0 !important;}",
          ".de-controls .form-control,",
          ".de-controls .selectize-input{width:100% !important;}"
        ))),
        card(
          class = "de-controls",
          card_header(
            class = "d-flex justify-content-between align-items-center",
            id = "hdr-controls",
            "Controls",
            bslib::tooltip(
              icon("circle-info", class = "text-secondary"),
              paste(
                "Dataset and thresholds are global - they drive the volcano",
                "colours, the table's up / down / NS calls, and the enrichment",
                "hit list."
              )
            )
          ),
          card_body(
            selectInput("dataset", "Dataset", choices = datasets),
            sliderInput(
              "lfc",
              "|log2 fold change| threshold",
              min = 0,
              max = 5,
              value = 1,
              step = 0.1
            ),
            sliderInput(
              "p",
              "Significance threshold",
              min = 0.001,
              max = 0.1,
              value = 0.05,
              step = 0.001
            ),
            radioButtons(
              "pcol",
              "Significance metric",
              choices = c("Adjusted p" = "padj", "Raw p" = "pvalue")
            ),
            conditionalPanel(
              "input.dataset == '__upload__'",
              # Opens the upload drawer (offcanvas) rather than showing the file
              # pickers inline; declarative Bootstrap toggle, no JS needed here.
              tags$button(
                class = "btn btn-sm btn-outline-primary w-100",
                type = "button",
                `data-bs-toggle` = "offcanvas",
                `data-bs-target` = "#de-upload-canvas",
                "Upload / change files…"
              )
            ),
            # Heatmap controls live here (not in the Heatmap card) so the plot
            # card stays uncluttered. Collapsed by default (native <details>, no
            # JS) since they are optional refinements. The gene selector also
            # carries the paste-a-list box.
            hr(),
            tags$details(
              tags$summary(
                class = "fw-semibold small",
                style = "cursor: pointer;",
                "Heatmap"
              ),
              div(
                class = "pt-2",
                gene_selector_ui("heatgenes", "Genes shown"),
                radioButtons(
                  "hscale",
                  "Values",
                  choices = c("Row z-score" = "row", "Expression" = "none")
                ),
                checkboxInput("hcluster", "Cluster genes", value = TRUE)
              )
            )
          )
        )
      )
    ),
    # Middle column: an "about this dataset" card, then the analysis plots, each
    # its own stacked row.
    column(
      width = 7,
      div(
        class = "d-flex flex-column gap-3",
        uiOutput("dataset_card"),
        card(
          full_screen = TRUE,
          card_header("PCA - sample overview", id = "hdr-pca"),
          card_help(
            "Principal components of the most-variable genes; each point is a",
            "sample, coloured by a metadata variable. Clear separation marks the",
            "dominant axis of variation - often tumour vs normal. Colour by batch",
            "to check for unwanted technical structure."
          ),
          layout_columns(
            col_widths = c(6, 6),
            uiOutput("pca_colour_ui"),
            selectInput(
              "pca_ntop",
              "Most-variable genes",
              choices = c("100", "250", "500", "All"),
              selected = "500"
            )
          ),
          pca_ui("pca")
        ),
        card(
          full_screen = TRUE,
          # Size to content (not a fill item), so the whole table shows and the card
          # grows with it -- no card-internal scrollbar stacked on the page scroll.
          fill = FALSE,
          card_header("Results table", id = "hdr-table"),
          card_help(
            "Every gene's fold change and significance. Select rows to drive the",
            "Heatmap; with nothing selected it shows the top genes by significance."
          ),
          checkboxInput("sigonly", "Significant genes only", value = FALSE),
          gene_table_ui("table", fill = FALSE)
        ),
        card(
          full_screen = TRUE,
          card_header("Gene detail", id = "hdr-detail"),
          card_help(
            "Expression of the focused gene across sample groups. Click a row in",
            "the Results table or a point in the Volcano to change which gene",
            "this shows."
          ),
          uiOutput("detail_gene_label"),
          group_comparison_ui("gdetail")
        ),
        card(
          full_screen = TRUE,
          card_header("Volcano", id = "hdr-volcano"),
          card_help(
            "Each point is a gene: log2 fold change (x) vs −log10 p (y). Dashed",
            "lines mark your thresholds; colour marks up / down / not-significant."
          ),
          sliderInput(
            "topn",
            "Max labels",
            min = 0,
            max = 30,
            value = 10,
            step = 1
          ),
          volcano_ui("volcano")
        ),
        card(
          full_screen = TRUE,
          card_header("Heatmap", id = "hdr-heatmap"),
          card_help(
            "Expression of the selected genes across samples. Row z-score",
            "standardises each gene; clustering reorders rows by similarity.",
            "Pick the genes and options under Heatmap in the left controls."
          ),
          heatmap_ui("heat")
        ),
        card(
          full_screen = TRUE,
          # Size to content so the full enrichment table shows without an inner
          # scrollbar (see the Results-table card above).
          fill = FALSE,
          card_header(
            "Enrichment - Hallmark over-representation",
            id = "hdr-enrichment"
          ),
          card_help(
            "MSigDB Hallmark pathways over-represented among the significant genes",
            "(hypergeometric test). Needs gene symbols - e.g. the TCGA-BRCA",
            "dataset. The dot plot shows the top sets (gene ratio on x, overlap as",
            "dot size, adjusted p as colour); the table lists them all."
          ),
          plotOutput("enrichment_dot", height = "520px"),
          DT::DTOutput("enrichment", fill = FALSE)
        )
      )
    ),
    # Right column: the Assistant chat, tall and sticky beside the plots so the
    # conversation has room while staying in view as the plot column scrolls.
    column(
      width = 3,
      div(
        id = "tour-assistant",
        class = "position-sticky",
        style = "top: 1rem;",
        byok_chat_ui(
          "chat",
          title = "DE assistant",
          subtitle = "Bring your own Gemini / OpenAI / Anthropic key.",
          height = "calc(100vh - 5rem)",
          sidebar_width = 420,
          show_tools = FALSE,
          starters = c(
            "Summarise this dataset and its design.",
            "What are the top up- and down-regulated genes?",
            "Which Hallmark pathways are enriched?",
            "Show MMP11, COL11A1 and NEK2 in the heatmap.",
            "Switch to the airway dataset.",
            "Only keep genes with adjusted p below 0.01."
          )
        )
      )
    )
  )
)

# --- About page: orientation + documentation -------------------------------
# One page: a quick orientation (what the tool does, how to start) followed by
# the reference material (data provenance, citations, methods, credits).
about_page <- div(
  class = "mx-auto my-3",
  style = "max-width: 900px;",
  card(
    id = "hdr-about",
    card_body(markdown(
      "## DE Explorer

Explore a differential-expression analysis interactively - from a whole-cohort
overview down to a single gene. Part of the **Lifescience Shiny Gallery**:
reusable Shiny apps and components for common bioinformatics workflows.

#### What you can do
- **PCA** - see how samples separate.
- **Results table** - browse and filter every gene; select rows to drive the heatmap.
- **Gene detail** - a selected gene's expression across sample groups.
- **Volcano** - effect size vs significance at your chosen thresholds.
- **Heatmap** - expression of the selected genes across samples.
- **Enrichment** - MSigDB Hallmark pathways over-represented among the hits,
  shown as a dot plot and a full table.
- **AI assistant** - an optional bring-your-own-key chat that reads the current
  views and can drive the controls for you.

#### Getting started
On the **Explorer** tab, pick a dataset in the left controls (the lung LUAD vs
LUSC set loads by default), set the fold-change and significance thresholds, then
work down the page. Selecting rows in the Results table drives the Heatmap; its
gene and display controls live under **Heatmap** in the left rail. New here?
Click **Demo** in the top bar for a guided tour, or open the **assistant** on the
right to ask about any view.

### Data
- **TCGA-BRCA** (`de-brca`) - The Cancer Genome Atlas breast-invasive-carcinoma
  cohort: primary tumour vs solid-tissue normal. Counts come from **recount3**,
  which uniformly re-aligns and quantifies public RNA-seq, so samples are
  directly comparable. We fit **DESeq2** and take VST-log2 expression, restricted
  to protein-coding genes. A curated subset (~40 tumour / 20 normal) ships with
  the app for a fast, reproducible demo; the full cohort has >1,000 tumours.
- **TCGA Lung** (`de-lung`, the default) - a **three-group** set: lung adenocarcinoma (LUAD)
  vs squamous-cell carcinoma (LUSC), plus solid-tissue normal, from the TCGA-LUAD
  and TCGA-LUSC cohorts via recount3 → DESeq2 → VST. The DE contrast is the
  tumour-subtype comparison **LUAD vs LUSC**; colour the PCA or gene-detail
  boxplots **by group** to see all three at once.
- **Airway** (`de-airway`) - dexamethasone-treated airway smooth-muscle cells, a
  classic DESeq2 dataset.
- **Synthetic** - a reproducible generator for testing.

Prep scripts under `data/prep/` are the source of truth (provenance + licensing).

#### Citations
- TCGA Network. *Comprehensive molecular portraits of human breast tumours.*
  Nature 490:61–70 (2012). doi:10.1038/nature11412
- TCGA Network. *Comprehensive molecular profiling of lung adenocarcinoma.*
  Nature 511:543–550 (2014). doi:10.1038/nature13385
- TCGA Network. *Comprehensive genomic characterization of squamous cell lung
  cancers.* Nature 489:519–525 (2012). doi:10.1038/nature11404
- Wilks C, et al. *recount3: summaries and queries for large-scale RNA-seq
  expression and splicing.* Genome Biol 22:323 (2021).
  doi:10.1186/s13059-021-02533-6
- Love MI, Huber W, Anders S. *Moderated estimation of fold change and dispersion
  for RNA-seq data with DESeq2.* Genome Biol 15:550 (2014).
  doi:10.1186/s13059-014-0550-8
- Liberzon A, et al. *The Molecular Signatures Database Hallmark gene set
  collection.* Cell Syst 1:417–425 (2015). doi:10.1016/j.cels.2015.12.004
- Himes BE, et al. *RNA-seq transcriptome profiling identifies CRISPLD2 as a
  glucocorticoid responsive gene in human airway smooth muscle cells.* PLoS One
  9:e99625 (2014). doi:10.1371/journal.pone.0099625

TCGA data are subject to the [NIH Genomic Data Sharing Policy](https://gdc.cancer.gov/access-data/data-access-policies);
the processed subset here is derived from open-access recount3 summaries.

### Methods
- **Volcano / table** classify each gene Up / Down / Not-significant from your
  |log2 fold change| and significance thresholds (adjusted or raw *p*).
- **PCA** runs on the most-variable genes.
- **Heatmap** shows per-gene expression, optionally row z-scored and clustered.
- **Enrichment** is hypergeometric over-representation (`stats::phyper`) of the
  significant genes against the MSigDB **Hallmark** collection, drawn as a dot
  plot (gene ratio, overlap size, adjusted *p*) and a table.
- **Multi-group datasets** (e.g. lung) colour the PCA and gene boxplots by group;
  the per-gene test switches to Kruskal-Wallis when there are more than two
  groups. The volcano and table always use one two-group DE contrast.

### Bring your own data
Match the DE data contract - `de_results.csv`, `expression.csv`, `metadata.csv` -
and choose *Upload your own…* in the dataset picker. See the data-contract and
reuse guides under the repository `docs/`.

### Credits
Built with **Shiny** + **bslib**. MIT © 2026 Posit Software, PBC. Authored by Samuel Bharti."
    ))
  )
)

ui <- page_navbar(
  title = "DE Explorer",
  theme = bslib::bs_theme(brand = "_brand.yml", primary = "#447099"),
  # Document-flow panels (not fill-the-viewport) so the Explorer rows sit at
  # their natural heights and the page scrolls.
  fillable = FALSE,
  id = "nav",
  nav_panel("Explorer", explorer_page, icon = icon("chart-column")),
  nav_panel("About", about_page, icon = icon("circle-info")),
  # Push the utility items to the right edge of the bar. Light mode only -- some
  # plots don't read well on a dark canvas, so no color-mode toggle.
  nav_spacer(),
  nav_item(
    actionLink(
      "demo",
      label = tagList(icon("circle-play"), "Demo"),
      class = "nav-link"
    )
  ),
  nav_item(
    tags$a(
      href = "https://github.com/posit-dev/lifescience-shiny-gallery",
      target = "_blank",
      rel = "noopener",
      class = "nav-link",
      icon("github"),
      "Source"
    )
  ),
  footer = div(
    class = "text-muted small text-center py-2 border-top",
    "DE Explorer · MIT © 2026 Posit Software, PBC · Authored by Samuel Bharti"
  )
)

server <- function(input, output, session) {
  # --- Guided demo tour (the "Demo" button in the navbar) -----------------
  # Walks a first-time user through the whole app: the input controls, then each
  # analysis card (highlighting its header), the assistant, and finally the
  # About page (cicerone switches to that nav tab for the last step).
  demo_guide <- cicerone::Cicerone$new(overlay_click_next = TRUE)$step(
    "hdr-controls",
    "1. Choose your data",
    paste(
      "Start here: pick a dataset (the lung LUAD vs LUSC set loads by",
      "default) and set the fold-change and significance thresholds. These",
      "are global and drive every view below."
    )
  )$step(
    "dataset_card",
    "About this dataset",
    "A quick summary of the loaded cohort: design, sample counts, source, and a link to the data portal."
  )$step(
    "hdr-pca",
    "PCA",
    "A principal-components overview of the samples. Colour by a metadata column (e.g. group) to see how they separate."
  )$step(
    "hdr-table",
    "Results table",
    "Every gene's fold change and significance. Select rows to drive the Heatmap; click a row to focus that gene."
  )$step(
    "hdr-detail",
    "Gene detail",
    "The focused gene's expression across sample groups, with a group-comparison test."
  )$step(
    "hdr-volcano",
    "Volcano",
    "Effect size vs significance; colour marks up / down / not-significant. Click a point to focus that gene."
  )$step(
    "hdr-heatmap",
    "Heatmap",
    "Expression of the selected genes. Its gene and display controls live under Heatmap in the left rail."
  )$step(
    "hdr-enrichment",
    "Enrichment",
    "MSigDB Hallmark pathways over-represented among the significant genes, as a dot plot and a table."
  )$step(
    "tour-assistant",
    "AI assistant",
    "Bring your own API key and ask about any view, or have it drive the controls for you."
  )$step(
    "a.nav-link[data-value='About']",
    "Learn more",
    "Finally, open the About page (this tab) for full data provenance, methods, and citations. That's the tour!",
    is_id = FALSE
  )
  observeEvent(input$demo, demo_guide$init()$start())

  # One shared dataset: a bundled contract dir, or the user's uploaded CSVs
  # (validated through the same contract).
  uploaded <- data_upload_validate_server(
    "de_upload",
    reader = read_de_dataset,
    files = de_upload_files
  )
  dataset <- reactive({
    if (identical(input$dataset, "__upload__")) {
      req(uploaded())
      uploaded()
    } else {
      read_de_dataset(file.path("data", input$dataset))
    }
  })
  de_results <- reactive(dataset()$de_results)

  # Bring-your-own-data drawer wiring. Selecting "Upload your own…" opens the
  # offcanvas; any bundled dataset is remembered so a cancelled upload can fall
  # back to it rather than leaving the app on an empty "__upload__" selection.
  prev_dataset <- reactiveVal(unname(datasets[[1]]))
  observeEvent(input$dataset, {
    if (identical(input$dataset, "__upload__")) {
      session$sendCustomMessage("open_de_upload", TRUE)
    } else {
      prev_dataset(input$dataset)
    }
  })
  observeEvent(input$de_upload_closed, {
    if (identical(input$dataset, "__upload__") && is.null(uploaded())) {
      updateSelectInput(session, "dataset", selected = prev_dataset())
    }
  })

  # --- About this dataset: disease/design, size, source, reference, links ---
  output$dataset_card <- renderUI({
    meta <- dataset()$metadata
    n <- nrow(meta)
    grp <- if ("group" %in% names(meta)) table(meta$group) else NULL
    grp_txt <- if (!is.null(grp)) {
      paste(sprintf("%s (n=%d)", names(grp), as.integer(grp)), collapse = ", ")
    }
    cols <- setdiff(names(meta), "sample")
    info <- dataset_info[[input$dataset]]
    if (is.null(info)) {
      info <- list(
        title = "Your uploaded dataset",
        design = NULL,
        source = "User-provided CSVs (matching the DE data contract)",
        portal = NULL,
        reference = NULL,
        doi = NULL,
        license = NULL
      )
    }
    line <- function(label, value) {
      if (is.null(value)) {
        NULL
      } else {
        tags$p(class = "mb-1", tags$strong(paste0(label, ": ")), value)
      }
    }
    card(
      card_header(info$title),
      card_body(
        class = "small",
        layout_columns(
          col_widths = c(6, 6),
          div(
            line("Design", info$design),
            tags$p(
              class = "mb-1",
              tags$strong("Samples: "),
              n,
              if (!is.null(grp_txt)) paste0(" - ", grp_txt)
            ),
            line("Metadata fields", paste(cols, collapse = ", "))
          ),
          div(
            line("Source", info$source),
            if (!is.null(info$reference)) {
              tags$p(
                class = "mb-1",
                tags$strong("Reference: "),
                info$reference,
                if (!is.null(info$doi)) {
                  tagList(
                    " ",
                    tags$a(
                      href = info$doi,
                      target = "_blank",
                      rel = "noopener",
                      "DOI"
                    )
                  )
                }
              )
            },
            line("License", info$license)
          )
        ),
        div(
          class = "d-flex gap-2 flex-wrap align-items-center mt-1",
          if (!is.null(info$portal)) {
            tags$a(
              href = info$portal,
              target = "_blank",
              rel = "noopener",
              class = "btn btn-sm btn-outline-secondary",
              icon("up-right-from-square"),
              paste0(" ", info$portal_label %||% "Data portal")
            )
          },
          actionLink("goto_about", "Read more on the About page →")
        )
      )
    )
  })
  # Jump to the About tab from the dataset card's link.
  observeEvent(input$goto_about, {
    bslib::nav_select("nav", "About")
  })

  # --- Assistant: scoped, tool-using BYOK chat ----------------------------
  # A plain (non-reactive) mirror of the app's current state. The assistant's
  # tools read it directly, so they are safe to call mid-stream (outside any
  # reactive context); it is kept current by an observer at the end of server().
  chat_state <- new.env(parent = emptyenv())

  # Genes the assistant asked the Heatmap to show (via set_heatmap_genes); NULL
  # means "follow the table selection / top-N seed" as usual.
  agent_heatmap_genes <- reactiveVal(NULL)

  # One shared "focus gene" unifies selection: it drives Gene detail and is
  # cross-highlighted in the Volcano, following the last gene the user clicked in
  # the Results table or the Volcano (default: the most significant gene).
  focus_gene <- reactiveVal(NULL)

  # Hard-scoped: the assistant only helps with THIS app + dataset, reads live
  # state through its tools, and declines anything off-topic.
  de_system_prompt <- paste(
    "You are the DE Explorer assistant, embedded in a differential-expression",
    "app showing one loaded dataset (e.g. TCGA-BRCA tumour vs normal). Your",
    "ONLY job is to help the user explore and interpret THIS app: its current",
    "dataset and its views -- PCA, results table, gene detail, volcano, heatmap,",
    "and MSigDB Hallmark over-representation enrichment.",
    "",
    "Before answering about a view, call the matching read tool for its live",
    "state: dataset_info, describe_pca, results_table, describe_volcano,",
    "describe_heatmap, describe_enrichment. Never invent gene names, counts, or",
    "statistics -- quote the tool output. Explain log2 fold change, adjusted",
    "p-values, PCA, and pathway terms plainly.",
    "",
    "You can also DRIVE the app's controls when the user asks -- then briefly say",
    "what you changed:",
    "- set_dataset: switch the loaded dataset.",
    "- set_thresholds: change the fold-change / significance cutoffs and metric",
    "  (drives the volcano, table, and enrichment together).",
    "- set_pca: change the PCA colour-by column or gene count.",
    "- set_focus_gene: focus a gene in Gene detail (also highlighted in volcano).",
    "- set_heatmap_genes: show specific genes in the heatmap.",
    "- set_heatmap_display: toggle row z-score vs expression, and clustering.",
    "- set_table_filter: show all genes or only significant ones.",
    "- set_volcano_labels: how many top genes the volcano labels.",
    "After changing a control, you may re-read the relevant view to interpret it.",
    "",
    "Refuse anything outside DE Explorer and this dataset: for off-topic or",
    "general questions, briefly decline and point back to what the app can do.",
    "Be concise.",
    sep = "\n"
  )

  # Read/interpret tools over the state mirror (guarded so the app still loads
  # without ellmer). Each returns a compact summary from the Shiny-free helpers
  # in R/_shared/de-summary.R.
  de_tools <- list()
  if (requireNamespace("ellmer", quietly = TRUE)) {
    de_tools <- list(
      ellmer::tool(
        function() {
          de_summarise_dataset(chat_state$dataset, chat_state$dataset_label)
        },
        name = "dataset_info",
        description = paste(
          "Meta on the currently selected dataset: sample and gene counts,",
          "groups, and metadata columns. Use for @dataset."
        )
      ),
      ellmer::tool(
        function() {
          de_summarise_pca(
            chat_state$dataset,
            chat_state$pca_colour,
            chat_state$pca_ntop
          )
        },
        name = "describe_pca",
        description = paste(
          "PCA view summary: variance explained by PC1/PC2 and group",
          "separation along PC1. Use for @pca."
        )
      ),
      ellmer::tool(
        function() {
          de_summarise_table(
            chat_state$dataset$de_results,
            chat_state$lfc,
            chat_state$p,
            chat_state$p_col
          )
        },
        name = "results_table",
        description = paste(
          "Results-table summary: up/down/NS counts and the top up- and",
          "down-regulated genes at the current thresholds. Use for @results."
        )
      ),
      ellmer::tool(
        function() {
          de_summarise_volcano(
            chat_state$dataset$de_results,
            chat_state$lfc,
            chat_state$p,
            chat_state$p_col
          )
        },
        name = "describe_volcano",
        description = paste(
          "Volcano summary: up/down/NS counts, the most significant genes, and",
          "the largest fold changes. Use for @volcano."
        )
      ),
      ellmer::tool(
        function() {
          de_summarise_heatmap(chat_state$dataset, chat_state$heatmap_genes)
        },
        name = "describe_heatmap",
        description = paste(
          "Heatmap summary: which genes are currently shown and the sample",
          "groups they span. Use for @heatmap."
        )
      ),
      ellmer::tool(
        function() {
          de_summarise_enrichment(
            chat_state$dataset$de_results,
            hallmark_sets,
            chat_state$lfc,
            chat_state$p,
            chat_state$p_col
          )
        },
        name = "describe_enrichment",
        description = paste(
          "Enrichment summary: top Hallmark pathways over-represented among the",
          "significant genes. Use for @enrichment."
        )
      ),
      ellmer::tool(
        function(genes) {
          valid <- intersect(genes, chat_state$dataset$de_results$gene)
          if (length(valid) == 0) {
            return(
              "None of those genes are in the current dataset; heatmap unchanged."
            )
          }
          agent_heatmap_genes(valid)
          paste0(
            "Heatmap updated to show ",
            length(valid),
            " gene(s): ",
            paste(valid, collapse = ", "),
            "."
          )
        },
        name = "set_heatmap_genes",
        description = paste(
          "Update the Heatmap to display the given gene symbols from the current",
          "dataset (replaces the shown selection). Use when the user asks to",
          "show or compare specific genes in the heatmap."
        ),
        arguments = list(
          genes = ellmer::type_array(
            items = ellmer::type_string("A gene symbol"),
            description = "Gene symbols to display in the heatmap"
          )
        )
      ),
      # --- Control tools: drive the app's inputs (updateXxxInput and the shared
      # reactiveVals are all safe to call mid-stream, outside a reactive context).
      ellmer::tool(
        function(dataset) {
          choices <- setdiff(unname(datasets), "__upload__")
          if (!dataset %in% choices) {
            return(paste0(
              "Unknown dataset. Choose one of: ",
              toString(choices)
            ))
          }
          updateSelectInput(session, "dataset", selected = dataset)
          paste0("Dataset switched to ", dataset, ".")
        },
        name = "set_dataset",
        description = paste(
          "Switch the loaded dataset. de-brca = TCGA-BRCA breast cancer (tumour",
          "vs normal); de-airway = airway dexamethasone; de-synthetic =",
          "reproducible synthetic set."
        ),
        arguments = list(
          dataset = ellmer::type_enum(
            setdiff(unname(datasets), "__upload__"),
            description = "The dataset id to load"
          )
        )
      ),
      ellmer::tool(
        function(lfc = NULL, p_threshold = NULL, significance_metric = NULL) {
          changed <- character(0)
          if (!is.null(lfc)) {
            lfc <- max(0, min(5, lfc))
            updateSliderInput(session, "lfc", value = lfc)
            changed <- c(changed, paste0("|log2FC| >= ", lfc))
          }
          if (!is.null(p_threshold)) {
            p_threshold <- max(0.001, min(0.1, p_threshold))
            updateSliderInput(session, "p", value = p_threshold)
            changed <- c(changed, paste0("p < ", p_threshold))
          }
          if (!is.null(significance_metric)) {
            updateRadioButtons(session, "pcol", selected = significance_metric)
            changed <- c(
              changed,
              paste0(
                "metric = ",
                if (identical(significance_metric, "padj")) {
                  "adjusted p"
                } else {
                  "raw p"
                }
              )
            )
          }
          if (length(changed) == 0) {
            return("No thresholds given; nothing changed.")
          }
          paste0("Thresholds updated: ", toString(changed), ".")
        },
        name = "set_thresholds",
        description = paste(
          "Change the significance thresholds that drive the volcano, results",
          "table, and enrichment together. Omit any argument to leave it",
          "unchanged. lfc = |log2 fold change| cutoff (0-5); p_threshold =",
          "significance cutoff (0.001-0.1); significance_metric = padj (adjusted)",
          "or pvalue (raw)."
        ),
        arguments = list(
          lfc = ellmer::type_number(
            "The |log2 fold change| cutoff, 0 to 5.",
            required = FALSE
          ),
          p_threshold = ellmer::type_number(
            "The significance cutoff, 0.001 to 0.1.",
            required = FALSE
          ),
          significance_metric = ellmer::type_enum(
            c("padj", "pvalue"),
            description = "Which p-value to threshold on.",
            required = FALSE
          )
        )
      ),
      ellmer::tool(
        function(colour_by = NULL, n_top = NULL) {
          changed <- character(0)
          if (!is.null(colour_by)) {
            cols <- setdiff(names(chat_state$dataset$metadata), "sample")
            if (!colour_by %in% cols) {
              return(paste0(
                "Unknown column. This dataset's metadata columns: ",
                toString(cols)
              ))
            }
            updateSelectInput(session, "pca_colour", selected = colour_by)
            changed <- c(changed, paste0("colour by ", colour_by))
          }
          if (!is.null(n_top)) {
            n_top <- as.character(n_top)
            choices <- c("100", "250", "500", "All")
            if (!n_top %in% choices) {
              return(paste0("n_top must be one of: ", toString(choices)))
            }
            updateSelectInput(session, "pca_ntop", selected = n_top)
            changed <- c(changed, paste0(n_top, " most-variable genes"))
          }
          if (length(changed) == 0) {
            return("Nothing to change for PCA.")
          }
          paste0("PCA updated: ", toString(changed), ".")
        },
        name = "set_pca",
        description = paste(
          "Change the PCA view: colour_by is a metadata column to colour samples",
          "by; n_top is how many most-variable genes to use (100, 250, 500, or",
          "All). Either may be omitted."
        ),
        arguments = list(
          colour_by = ellmer::type_string(
            "Metadata column to colour PCA points by.",
            required = FALSE
          ),
          n_top = ellmer::type_string(
            "Most-variable gene count: 100, 250, 500, or All.",
            required = FALSE
          )
        )
      ),
      ellmer::tool(
        function(gene) {
          if (!gene %in% chat_state$dataset$de_results$gene) {
            return(paste0("'", gene, "' is not in the current dataset."))
          }
          focus_gene(gene)
          paste0("Gene detail now focuses ", gene, ".")
        },
        name = "set_focus_gene",
        description = paste(
          "Focus a single gene in the Gene detail view (its expression by",
          "group); the gene is also highlighted in the volcano. Use when the user",
          "asks to look at one specific gene."
        ),
        arguments = list(
          gene = ellmer::type_string("A gene symbol from the current dataset")
        )
      ),
      ellmer::tool(
        function(scale = NULL, cluster = NULL) {
          changed <- character(0)
          if (!is.null(scale)) {
            updateRadioButtons(session, "hscale", selected = scale)
            changed <- c(
              changed,
              paste0(
                "values = ",
                if (identical(scale, "row")) "row z-score" else "expression"
              )
            )
          }
          if (!is.null(cluster)) {
            updateCheckboxInput(session, "hcluster", value = cluster)
            changed <- c(
              changed,
              paste0("clustering ", if (isTRUE(cluster)) "on" else "off")
            )
          }
          if (length(changed) == 0) {
            return("Nothing to change for the heatmap display.")
          }
          paste0("Heatmap display updated: ", toString(changed), ".")
        },
        name = "set_heatmap_display",
        description = paste(
          "Change how the heatmap renders: scale is 'row' (z-score each gene) or",
          "'none' (raw expression); cluster reorders rows by similarity. Either",
          "may be omitted."
        ),
        arguments = list(
          scale = ellmer::type_enum(
            c("row", "none"),
            description = "Row z-score ('row') or raw expression ('none').",
            required = FALSE
          ),
          cluster = ellmer::type_boolean(
            "Whether to cluster (reorder) the heatmap rows.",
            required = FALSE
          )
        )
      ),
      ellmer::tool(
        function(significant_only) {
          updateCheckboxInput(session, "sigonly", value = significant_only)
          paste0(
            "Results table now shows ",
            if (isTRUE(significant_only)) "only significant" else "all",
            " genes."
          )
        },
        name = "set_table_filter",
        description = paste(
          "Filter the results table: TRUE shows only significant genes at the",
          "current thresholds; FALSE shows all genes."
        ),
        arguments = list(
          significant_only = ellmer::type_boolean(
            "Show only significant genes?"
          )
        )
      ),
      ellmer::tool(
        function(max_labels) {
          max_labels <- as.integer(max(0, min(30, max_labels)))
          updateSliderInput(session, "topn", value = max_labels)
          paste0("Volcano now labels up to ", max_labels, " top genes.")
        },
        name = "set_volcano_labels",
        description = paste(
          "Set how many of the top genes the volcano plot labels (0 to 30)."
        ),
        arguments = list(
          max_labels = ellmer::type_integer(
            "Number of top genes to label, 0 to 30."
          )
        )
      )
    )
  }

  byok_chat_server(
    "chat",
    system_prompt = de_system_prompt,
    tools = de_tools
  )

  # --- Enrichment: Hallmark pathways over-represented in the DE hits -------
  # One computation feeds both the dot plot and the table.
  enrichment_res <- reactive({
    dr <- de_results()
    status <- de_status(dr$logFC, dr[[input$pcol]], input$lfc, input$p)
    enrichment_ora(
      hits = dr$gene[status != "NS"],
      gene_sets = hallmark_sets,
      universe = dr$gene
    )
  })

  # Dot plot: the classic enrichment view -- gene ratio (fraction of the set that
  # are hits) on x, overlap size as the dot size, adjusted-p as the colour, top
  # sets by significance. Reads better at a glance than the table alone.
  output$enrichment_dot <- renderPlot({
    res <- enrichment_res()
    shiny::validate(shiny::need(
      nrow(res) > 0,
      "No enriched Hallmark sets (need gene symbols overlapping Hallmark)."
    ))
    top <- utils::head(res[order(res$p_adj), , drop = FALSE], 15)
    top$gene_ratio <- top$n_hits / top$set_size
    # Tidy the Hallmark labels (drop the HALLMARK_ prefix, underscores -> spaces).
    top$label <- tolower(gsub("_", " ", sub("^HALLMARK_", "", top$gene_set)))
    top$label <- factor(top$label, levels = rev(top$label[order(top$p_adj)]))
    ggplot2::ggplot(
      top,
      ggplot2::aes(x = gene_ratio, y = label)
    ) +
      ggplot2::geom_point(ggplot2::aes(size = n_hits, colour = p_adj)) +
      ggplot2::scale_colour_gradientn(
        colours = ltc_gradient(),
        trans = "reverse",
        name = "adj. p"
      ) +
      ggplot2::scale_size_continuous(name = "overlap", range = c(3, 11)) +
      ggplot2::labs(x = "gene ratio (hits / set size)", y = NULL) +
      ggplot2::theme_minimal(base_size = 16) +
      ggplot2::theme(panel.grid.minor = ggplot2::element_blank())
  })

  output$enrichment <- DT::renderDT(
    {
      res <- enrichment_res()
      shiny::validate(shiny::need(
        nrow(res) > 0,
        "No enriched Hallmark sets (need gene symbols overlapping Hallmark)."
      ))
      DT::datatable(
        res,
        rownames = FALSE,
        selection = "none",
        class = "cell-border stripe hover",
        extensions = "Buttons",
        options = list(
          dom = "Bfrtip",
          buttons = list("copy", "csv"),
          pageLength = 15
        )
      )
    },
    server = TRUE
  )

  # --- Gene detail: the focused gene's expression by group ----------------
  # Default the focus to the most significant gene whenever the dataset loads.
  observeEvent(de_results(), {
    dr <- de_results()
    focus_gene(dr$gene[order(dr$padj, na.last = TRUE)][1])
  })
  output$detail_gene_label <- renderUI({
    g <- focus_gene()
    if (is.null(g)) {
      return(tags$p(
        class = "text-muted small mb-2",
        "Click a gene in the Results table or the Volcano."
      ))
    }
    tags$p(
      class = "mb-2",
      "Showing ",
      tags$strong(g),
      tags$span(
        class = "text-muted small",
        " - click another table row or volcano point to change."
      )
    )
  })
  group_comparison_server(
    "gdetail",
    values = reactive({
      g <- req(focus_gene())
      m <- de_expression_matrix(dataset())
      req(g %in% rownames(m))
      m[g, ]
    }),
    metadata = reactive(dataset()$metadata),
    value_label = reactive(paste(req(focus_gene()), "expression")),
    group_col = reactive("group")
  )

  # --- Volcano (click a point to focus that gene) --------------------------
  vol <- volcano_server(
    "volcano",
    de_results = de_results,
    lfc_threshold = reactive(input$lfc),
    p_threshold = reactive(input$p),
    p_col = reactive(input$pcol),
    label_top_n = reactive(input$topn),
    highlight = reactive(focus_gene())
  )
  observeEvent(vol$clicked(), {
    g <- vol$clicked()
    if (!is.null(g)) {
      focus_gene(g)
    }
  })

  # --- Results table (row selection is the shared gene selection) ----------
  table_res <- gene_table_server(
    "table",
    de_results = de_results,
    lfc_threshold = reactive(input$lfc),
    p_threshold = reactive(input$p),
    p_col = reactive(input$pcol),
    sig_only = reactive(input$sigonly)
  )
  # Clicking a table row focuses that gene in Gene detail + the Volcano.
  observeEvent(table_res$clicked(), {
    g <- table_res$clicked()
    if (!is.null(g)) {
      focus_gene(g)
    }
  })

  # Clear the table's row selection when the dataset changes, so the heatmap is
  # never driven by row indices that pointed into the previous dataset (DT keeps
  # the prior selection until its client re-render). The module's DT output is
  # at the "table" namespace, hence "table-tbl".
  observeEvent(input$dataset, {
    DT::selectRows(DT::dataTableProxy("table-tbl"), NULL)
    agent_heatmap_genes(NULL)
  })

  # When the user drives the table selection, hand the heatmap back to them:
  # drop any gene set the assistant had pushed via set_heatmap_genes.
  observeEvent(
    table_res$selected(),
    agent_heatmap_genes(NULL),
    ignoreInit = TRUE
  )

  # Genes feeding the heatmap: the table's selection (intersected with the
  # current dataset's genes, so a stale or out-of-range selection can't drive or
  # error the heatmap), else the top-N by the chosen significance metric so the
  # heatmap is never empty.
  selected_genes <- reactive({
    sel <- intersect(table_res$selected(), de_results()$gene)
    if (length(sel) > 0) {
      return(sel)
    }
    dr <- de_results()
    utils::head(
      dr$gene[order(dr[[input$pcol]], na.last = TRUE)],
      default_heatmap_n
    )
  })

  # --- Heatmap -------------------------------------------------------------
  # The gene-selector is seeded from the shared selection -- the assistant's
  # pushed genes (set_heatmap_genes) take precedence, else the table rows /
  # top-N -- and is then the source of truth for the heatmap rows, so users can
  # refine the gene set or paste their own; it falls back to the seed when
  # cleared.
  heat_genes <- gene_selector_server(
    "heatgenes",
    choices = reactive(de_results()$gene),
    selected = reactive({
      ag <- agent_heatmap_genes()
      if (!is.null(ag)) ag else selected_genes()
    })
  )
  # Intersect the selectize's picks with the current dataset's genes: on a
  # dataset switch the selectize still holds the previous dataset's genes for a
  # round-trip, which would otherwise be passed straight to (and error) the
  # heatmap. Fall back to the seed set when nothing valid is picked.
  heatmap_rows <- reactive({
    picked <- intersect(heat_genes(), de_results()$gene)
    if (length(picked) > 0) picked else selected_genes()
  })
  heatmap_server(
    "heat",
    matrix = reactive(de_expression_matrix(dataset())),
    rows = heatmap_rows,
    metadata = reactive(dataset()$metadata),
    scale = reactive(input$hscale),
    cluster_rows = reactive(input$hcluster)
  )

  # --- PCA -----------------------------------------------------------------
  # Colour-by choices depend on the dataset's metadata (group/batch vs cell).
  output$pca_colour_ui <- renderUI({
    cols <- setdiff(names(dataset()$metadata), "sample")
    selectInput("pca_colour", "Colour samples by", choices = cols)
  })
  pca_server(
    "pca",
    dataset = dataset,
    colour_by = reactive(input$pca_colour),
    n_top = reactive(
      if (identical(input$pca_ntop, "All")) NULL else as.integer(input$pca_ntop)
    )
  )

  # --- Keep the assistant's state mirror current --------------------------
  # Reads reactives in a reactive context and writes plain values into the env
  # the assistant tools read (see the tool definitions above).
  observe({
    chat_state$dataset <- dataset()
    chat_state$dataset_label <- names(datasets)[match(input$dataset, datasets)]
    chat_state$lfc <- input$lfc
    chat_state$p <- input$p
    chat_state$p_col <- input$pcol
    chat_state$pca_colour <- input$pca_colour %||% "group"
    chat_state$pca_ntop <- if (identical(input$pca_ntop, "All")) {
      NULL
    } else {
      as.integer(input$pca_ntop)
    }
    chat_state$heatmap_genes <- heatmap_rows()
  })
}

shinyApp(ui, server)
