# Drug Perturbation Explorer (classic Shiny) -- connectivity analysis in the
# spirit of CMap / LINCS: score reference perturbations against a query
# signature (up / down genes) to find drugs that mimic or reverse it.
#
# App (L3) layer: page layout + wiring only. Compute lives in the logic layer
# (R/_shared, Shiny-free); UI in the component modules (R/_modules).
#
# Vendored copy. This directory is self-contained: it runs and deploys on its
# own, with its own modules and its own data. Upstream is
# posit-dev/lifescience-shiny-gallery, where R/_shared and R/_modules are
# generated by scripts/sync-shared.R and git-ignored; here they are checked in.
# Change them upstream and re-copy rather than editing them in place.
#
# No bslib: this app ships a bespoke, bslib-free UI (frontend-design; see
# www/app.css). Its navigation is deliberately distinct from the other gallery
# apps -- a vertical activity-bar rail + a master-detail leaderboard. The
# assistant is rebuilt bslib-free (byok_chat_ui_plain) reusing the byok-chat
# SERVER unchanged.

# Dev convenience: load a local, git-ignored .Renviron (e.g. BYOK API keys) from
# the app dir or any parent up to the repo root, so Sys.getenv() sees them when
# the app is launched from its own working directory. A no-op when absent.
local({
  dir <- normalizePath(".", mustWork = FALSE)
  repeat {
    f <- file.path(dir, ".Renviron")
    if (file.exists(f)) {
      readRenviron(f)
      break
    }
    parent <- dirname(dir)
    if (identical(parent, dir)) {
      break
    }
    dir <- parent
  }
})

library(shiny)
library(ggplot2)
library(DT)

# Logic layer first (functions the modules call), then the component modules.
for (f in list.files("R/_shared", pattern = "[.][Rr]$", full.names = TRUE)) {
  source(f)
}
for (f in list.files("R/_modules", pattern = "[.][Rr]$", full.names = TRUE)) {
  source(f)
}

# Bundled reference panels (each a perturbation_dataset dir + an example query).
datasets <- c(
  "Synthetic (BRCA-grounded)" = "perturbation-synthetic",
  "LINCS L1000 - MCF7 (real)" = "perturbation-lincs",
  "Upload your own…" = "__upload__"
)
n_side <- 10L # top mimics + top reversers shown in the hits heatmap

# Descriptive metadata per bundled panel, for the "Reference panel" card.
dataset_info <- list(
  "perturbation-synthetic" = list(
    title = "Synthetic (BRCA-grounded)",
    design = "Simulated reference perturbations over the TCGA-BRCA gene space",
    source = "Seeded generator in data/prep - a reproducible testing fixture",
    portal = NULL,
    portal_label = NULL,
    reference = "Not applicable (synthetic fixture)",
    doi = NULL,
    license = "MIT (this repository)"
  ),
  "perturbation-lincs" = list(
    title = "LINCS L1000 - MCF7",
    design = "Small-molecule perturbations profiled in the MCF7 breast line",
    source = "LINCS L1000 (Connectivity Map / CLUE), level-5 signatures",
    portal = "https://clue.io/",
    portal_label = "CLUE - Connectivity Map",
    reference = "Subramanian A et al., Cell 171:1437–1452 (2017)",
    doi = "https://doi.org/10.1016/j.cell.2017.10.049",
    license = "CC BY 4.0 (Broad Institute LINCS)"
  )
)

# Perturbation contract files, for the "upload your own" path.
drug_upload_files <- c(
  profiles = "profiles.csv",
  pert_meta = "pert_meta.csv"
)

# --- Assistant UI, rebuilt without bslib -----------------------------------
# Reuses byok_chat_server (and the module's provider/env helpers) unchanged; only
# the presentation is bslib-free. Inputs/outputs are namespaced under `id` exactly
# as the server expects; the chat is shinychat's web component.
byok_chat_ui_plain <- function(
  id,
  title,
  subtitle = NULL,
  providers = c("gemini", "openai", "anthropic"),
  starters = NULL,
  placeholder = "Ask me anything...",
  height = "100%"
) {
  ns <- NS(id)
  providers <- .byok_chat_providers(providers)
  if (!.byok_chat_packages_ok() || length(providers) == 0) {
    return(tagList(
      div(
        class = "drawer-head",
        div(h2(title)),
        tags$button(
          class = "drawer-close",
          onclick = "DP.closeDrawer('assistant_drawer')",
          HTML("&times;")
        )
      ),
      div(
        class = "drawer-body",
        tags$p(
          "The AI assistant is off because its packages (ellmer, shinychat)",
          "are not installed."
        )
      )
    ))
  }
  choices <- .byok_chat_provider_choices(providers)
  greeting <- if (
    nzchar(.byok_chat_env_first(.byok_chat_provider_meta(providers[1])$env))
  ) {
    paste(
      "Hi! A key was found in your environment - open **Model & key** below,",
      "pick a model, and click **Connect** to start chatting."
    )
  } else {
    paste(
      "Hi! Open **Model & key** below, paste an API key, and click",
      "**Connect** to start chatting."
    )
  }
  if (length(starters) > 0) {
    cards <- paste0(
      "- <span class=\"suggestion submit\">",
      vapply(unname(starters), htmltools::htmlEscape, character(1)),
      "</span>"
    )
    greeting <- paste0(greeting, "\n\n", paste(cards, collapse = "\n"))
  }
  tagList(
    tags$style(HTML(paste0(
      "#",
      ns("chat"),
      " .shiny-tool-request,#",
      ns("chat"),
      " .shiny-tool-result{display:none !important;}"
    ))),
    div(
      class = "drawer-head",
      div(h2(title), if (!is.null(subtitle)) div(class = "sub", subtitle)),
      div(
        style = "display:flex;align-items:center;gap:0.6rem;",
        uiOutput(ns("conn_badge"), inline = TRUE),
        tags$button(
          class = "drawer-close",
          onclick = "DP.closeDrawer('assistant_drawer')",
          HTML("&times;")
        )
      )
    ),
    tags$details(
      class = "byok",
      tags$summary(icon("gear"), " Model & key"),
      div(
        class = "byok-body",
        selectInput(
          ns("provider"),
          "Provider",
          choices = choices,
          selected = unname(choices)[1]
        ),
        uiOutput(ns("key_help")),
        passwordInput(
          ns("api_key"),
          "API key",
          placeholder = "Paste your key (kept in this session only)"
        ),
        selectizeInput(
          ns("model"),
          "Model",
          choices = character(0),
          selected = character(0),
          multiple = FALSE,
          options = list(
            create = TRUE,
            placeholder = "Provider default - pick or type a model"
          )
        ),
        actionButton(
          ns("refresh_models"),
          "List models for this key",
          class = "btn-line"
        ),
        uiOutput(ns("model_source")),
        div(
          style = "display:flex;gap:0.5rem;margin:0.6rem 0;",
          actionButton(ns("connect"), "Connect", class = "btn-line btn-fill"),
          actionButton(ns("forget"), "Forget key", class = "btn-line")
        ),
        uiOutput(ns("cred_status"))
      )
    ),
    div(
      class = "drawer-body chat",
      shinychat::chat_ui(
        ns("chat"),
        height = height,
        placeholder = placeholder,
        greeting = greeting
      )
    )
  )
}

# Client-side glue: vertical-rail page nav (plain show/hide + resize dispatch),
# slide-in drawers + scrim, and the upload-drawer open/close bridge to the server.
DP_JS <- paste0(
  "window.DP={",
  "_scrim:function(){return document.getElementById('scrim');},",
  "openDrawer:function(id){var d=document.getElementById(id);",
  "if(d){d.classList.add('open');DP._scrim().classList.add('show');}},",
  "closeDrawer:function(id){var d=document.getElementById(id);",
  "if(d){d.classList.remove('open');}DP._sync();},",
  "toggleDrawer:function(id){var d=document.getElementById(id);",
  "if(d&&d.classList.contains('open'))DP.closeDrawer(id);else DP.openDrawer(id);},",
  "openQuery:function(){DP.openDrawer('query_drawer');},",
  "openUpload:function(){DP.openDrawer('upload_drawer');},",
  "closeUpload:function(){DP.closeDrawer('upload_drawer');",
  "if(window.Shiny&&Shiny.setInputValue)Shiny.setInputValue('dp_upload_closed',Date.now());},",
  "closeAll:function(){var u=document.getElementById('upload_drawer');",
  "var uo=u&&u.classList.contains('open');",
  "document.querySelectorAll('.drawer.open').forEach(function(d){d.classList.remove('open');});",
  "if(uo&&window.Shiny&&Shiny.setInputValue)Shiny.setInputValue('dp_upload_closed',Date.now());DP._sync();},",
  "_sync:function(){if(!document.querySelector('.drawer.open'))DP._scrim().classList.remove('show');},",
  "_resize:function(){setTimeout(function(){window.dispatchEvent(new Event('resize'));},60);},",
  "nav:function(name){document.querySelectorAll('.rail-nav .navlink[data-page]').forEach(function(a){",
  "a.classList.toggle('active',a.getAttribute('data-page')===name);});",
  "document.querySelectorAll('.page-section[data-page]').forEach(function(s){",
  "s.style.display=(s.getAttribute('data-page')===name)?'block':'none';});",
  "DP._resize();window.scrollTo({top:0,behavior:'smooth'});},",
  # Demo must run on the Workbench with no drawer covering the targets: reset the
  # UI, then fire the `demo` input once the DOM has settled.
  "startDemo:function(){DP.closeAll();DP.nav('Workbench');",
  "setTimeout(function(){if(window.Shiny&&Shiny.setInputValue)",
  "Shiny.setInputValue('demo',Date.now(),{priority:'event'});},420);}",
  "};",
  "document.addEventListener('DOMContentLoaded',function(){",
  "if(window.Shiny){Shiny.addCustomMessageHandler('open_dp_upload',function(x){DP.openUpload();});}});"
)

# Collapsible per-panel guidance: a small muted <details> toggle.
card_help <- function(...) {
  tags$details(
    class = "help",
    tags$summary("How to read this"),
    div(class = "body", ...)
  )
}

# A designed section (bslib-free "card"): eyebrow + title head, then body.
dp_panel <- function(id, eyebrow, title, ..., class = NULL) {
  div(
    class = paste("panel", class),
    id = id,
    div(
      class = "panel-head",
      div(class = "eyebrow", eyebrow),
      h3(class = "panel-title", title)
    ),
    div(class = "panel-body", ...)
  )
}

# --- Query editor drawer (the up / down gene builder) ----------------------
# Editing the query lives in a slide-in drawer so the workbench stays uncluttered;
# a compact summary + "Edit signature" button in the console opens it.
query_drawer <- div(
  class = "drawer",
  id = "query_drawer",
  div(
    class = "drawer-head",
    div(
      h2("Query signature"),
      div(class = "sub", "Up / down genes to match perturbations against.")
    ),
    tags$button(
      class = "drawer-close",
      onclick = "DP.closeDrawer('query_drawer')",
      HTML("&times;")
    )
  ),
  div(
    class = "drawer-body",
    div(
      class = "drawer-copy",
      tags$p(
        "Everything downstream re-scores against this query. Prefilled with the",
        "panel's example (a TCGA-BRCA tumour-vs-normal signature); edit the",
        "selections or paste your own gene lists."
      )
    ),
    gene_selector_ui("qup", "Up genes"),
    gene_selector_ui("qdown", "Down genes")
  )
)

# --- Bring-your-own-data drawer --------------------------------------------
upload_drawer <- div(
  class = "drawer",
  id = "upload_drawer",
  div(
    class = "drawer-head",
    div(
      h2("Upload your own panel"),
      div(class = "sub", "Two CSVs matching the perturbation data contract.")
    ),
    tags$button(
      class = "drawer-close",
      onclick = "DP.closeUpload()",
      HTML("&times;")
    )
  ),
  div(
    class = "drawer-body",
    div(
      class = "drawer-copy",
      tags$p(
        "Provide two CSV files matching the perturbation data contract. Column",
        "names must match exactly (case-sensitive) - the panel is rejected",
        "otherwise, with the reason shown below."
      ),
      tags$ul(
        tags$li(
          tags$code("profiles.csv"),
          " - a ",
          tags$code("gene"),
          " column plus one numeric column per perturbation (per-gene",
          " z-scores); column names must match the pert_ids in pert_meta."
        ),
        tags$li(
          tags$code("pert_meta.csv"),
          " - one row per perturbation. Required columns: ",
          tags$code(toString(perturbation_meta_required)),
          "."
        )
      ),
      tags$p(
        class = "muted",
        "Every profile column must have a matching pert_meta row (and vice",
        "versa); build the up / down query once loaded."
      )
    ),
    tags$hr(),
    data_upload_validate_ui("dp_upload", drug_upload_files)
  )
)

# --- Vertical activity rail: the navigation --------------------------------
rail_nav <- tags$aside(
  class = "rail-nav",
  div(
    class = "rail-brand",
    div(class = "mark", icon("capsules")),
    div(class = "wm", "Drug", tags$br(), "Pert")
  ),
  tags$a(
    class = "navlink active",
    `data-page` = "Workbench",
    onclick = "DP.nav('Workbench')",
    icon("table-cells-large"),
    div(class = "lab", "Workbench")
  ),
  tags$a(
    class = "navlink",
    `data-page` = "About",
    onclick = "DP.nav('About')",
    icon("circle-info"),
    div(class = "lab", "About")
  ),
  div(class = "rail-spacer"),
  div(
    class = "rail-bottom",
    tags$a(
      class = "navlink",
      id = "open_assistant",
      onclick = "DP.toggleDrawer('assistant_drawer')",
      icon("robot"),
      div(class = "lab", "Assistant")
    ),
    tags$a(
      class = "navlink",
      onclick = "DP.startDemo()",
      icon("circle-play"),
      div(class = "lab", "Demo")
    ),
    tags$a(
      class = "navlink",
      href = "https://github.com/posit-dev/lifescience-shiny-gallery",
      target = "_blank",
      rel = "noopener",
      icon("github"),
      div(class = "lab", "Source")
    )
  )
)

# --- Workbench: the interactive tool ---------------------------------------
workbench_page <- tagList(
  # Query console: global controls + a compact query summary. Sticky at the top.
  div(
    class = "console",
    id = "controls_panel",
    div(
      class = "cfield",
      style = "width:240px;",
      selectInput("dataset", "Reference panel", choices = datasets)
    ),
    div(
      class = "cfield",
      style = "min-width:190px;",
      radioButtons(
        "method",
        "Connectivity score",
        choices = c("Weighted (WTCS)" = "wtcs", "Cosine" = "cosine"),
        inline = TRUE
      )
    ),
    div(
      class = "cfield",
      style = "width:250px;",
      sliderInput(
        "thr",
        "Mimic / reverser threshold",
        min = 0,
        max = 1,
        value = 0.3,
        step = 0.05
      )
    ),
    div(
      class = "cfield grow",
      id = "hdr-query",
      tags$label("Query signature"),
      div(
        class = "query-row",
        uiOutput("query_summary", inline = TRUE),
        tags$button(
          type = "button",
          class = "btn-line",
          onclick = "DP.openQuery()",
          icon("pen-to-square"),
          " Edit signature"
        )
      )
    )
  ),
  div(
    class = "work",
    uiOutput("stat_ribbon"),
    uiOutput("dataset_card"),
    div(
      class = "md-grid",
      div(
        class = "md-master",
        dp_panel(
          "hdr-connectivity",
          "Ranked",
          "Connectivity leaderboard - select a hit",
          class = "hero",
          card_help(
            "Every reference perturbation ranked by connectivity to your query.",
            "A positive score mimics the signature; a negative score reverses it",
            "(a repurposing candidate). Select a row to inspect that hit in",
            "Compound detail."
          ),
          connectivity_table_ui("ct")
        ),
        dp_panel(
          "hdr-distribution",
          "Spread",
          "Score distribution",
          card_help(
            "How connectivity scores spread across the whole panel. The dashed",
            "lines mark your mimic / reverser threshold; the highlight marks the",
            "score of the hit selected in the leaderboard."
          ),
          score_distribution_ui("dist")
        )
      ),
      div(
        class = "md-detail",
        dp_panel(
          "hdr-detail",
          "Selected",
          "Compound detail",
          card_help(
            "The selected hit's mechanism of action (MOA) across the panel:",
            "connectivity scores of every perturbation sharing that MOA, broken",
            "down by cell line or dose."
          ),
          uiOutput("detail_header"),
          radioButtons(
            "detail_by",
            "Break down by",
            choices = c("Cell line" = "cell_line", "Dose" = "dose"),
            inline = TRUE
          ),
          div(
            class = "muted",
            style = "font-size:0.8rem;margin:0.2rem 0 0.5rem;",
            textOutput("detail_label", inline = TRUE)
          ),
          group_comparison_ui("detail")
        )
      )
    ),
    dp_panel(
      "hdr-heatmap",
      "Landscape",
      "Top-hits heatmap - query genes across the strongest hits",
      card_help(
        "Query genes (rows) across the strongest mimics and reversers (columns).",
        "Row z-score standardises each gene so the direction of each",
        "perturbation's effect is comparable."
      ),
      heatmap_ui("hits")
    )
  )
)

# --- About page ------------------------------------------------------------
about_page <- div(
  class = "about",
  markdown(
    "## Drug Perturbation Explorer

Find drugs whose transcriptional effect **mimics** or **reverses** a query
signature - connectivity analysis in the spirit of the **Connectivity Map**
(CMap) and **LINCS L1000**. Part of the **Lifescience Shiny Gallery**: reusable
Shiny apps and components for common bioinformatics workflows.

#### What you can do
- **Query signature** - build an up / down gene set (prefilled from a real DE
  contrast) in the slide-in editor; everything re-scores against it.
- **Connectivity leaderboard** - every reference perturbation ranked by
  connectivity; select a hit to inspect it.
- **Score distribution** - how scores spread, with your threshold and the
  selected hit marked.
- **Compound detail** - a hit's mechanism of action (MOA) broken down by cell
  line or dose.
- **Top-hits heatmap** - query genes across the strongest mimics and reversers.

#### Getting started
In the **Workbench**, pick a reference panel, connectivity score, and threshold
in the query console at the top, then click **Edit signature** to adjust the up /
down query in a slide-in editor. The connectivity leaderboard ranks every
perturbation; select a row to drive the Score distribution highlight and Compound
detail. Open the **Assistant** from the left rail to ask about any view or have
it drive the controls.

### Data
- **Synthetic (BRCA-grounded)** (`perturbation-synthetic`) - simulated reference
  perturbations over the TCGA-BRCA gene space, a clean and reproducible demo.
- **LINCS L1000 - MCF7** (`perturbation-lincs`) - a real panel of small-molecule
  perturbations profiled in the MCF7 breast-cancer line, from the LINCS L1000 /
  Connectivity Map resource. Real connectivity scores are modest - lower the
  threshold to surface hits.

Prep scripts under `data/prep/` are the source of truth (provenance + licensing).

#### Citations
- Subramanian A, et al. *A Next Generation Connectivity Map: L1000 Platform and
  the First 1,000,000 Profiles.* Cell 171:1437–1452 (2017).
  doi:10.1016/j.cell.2017.10.049
- Lamb J, et al. *The Connectivity Map: using gene-expression signatures to
  connect small molecules, genes, and disease.* Science 313:1929–1935 (2006).
  doi:10.1126/science.1132939
- TCGA Network. *Comprehensive molecular portraits of human breast tumours.*
  Nature 490:61–70 (2012). doi:10.1038/nature11412

LINCS L1000 data are released by the Broad Institute under
[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/); the subset here is
derived from level-5 signatures.

### Methods
- **Connectivity score** classifies each perturbation from your query's up /
  down genes. **Weighted (WTCS)** combines the weighted-KS enrichment of the up
  and down sets (positive = mimic, negative = reverser); **Cosine** is cosine
  similarity to the query vector.
- **Mimic / reverser calls** apply your |score| threshold: above +t is a Mimic,
  below -t a Reverser, in between Neutral.
- **Top-hits heatmap** shows the query genes across the strongest mimics and
  reversers, optionally row z-scored.

### Bring your own data
Match the perturbation data contract - `profiles.csv`, `pert_meta.csv` - and
choose *Upload your own…* in the panel picker. See the data-contract and reuse
guides under the repository `docs/`.

### Credits
Built with **Shiny**. MIT © 2026 Posit Software, PBC. Authored by Samuel Bharti."
  )
)

ui <- tagList(
  tags$head(
    tags$meta(
      name = "viewport",
      content = "width=device-width, initial-scale=1"
    ),
    tags$title("Drug Perturbation"),
    tags$link(rel = "preconnect", href = "https://fonts.googleapis.com"),
    tags$link(
      rel = "preconnect",
      href = "https://fonts.gstatic.com",
      crossorigin = NA
    ),
    tags$link(
      rel = "stylesheet",
      href = paste0(
        # Instrument Sans (UI + display) + JetBrains Mono (data/labels): an
        # all-sans "instrument" voice, distinct from Signature Scoring's serif.
        "https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@400;",
        "500;600;700&family=JetBrains+Mono:wght@400;500&display=swap"
      )
    ),
    tags$link(
      rel = "stylesheet",
      href = paste0("app.css?v=", as.integer(file.info("www/app.css")$mtime))
    ),
    # shinychat's version gate reads window.bootstrap.Tab.VERSION; load Bootstrap
    # 5's JS bundle (a plain CDN script, not bslib) so the gate is satisfied.
    tags$script(
      src = paste0(
        "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/",
        "bootstrap.bundle.min.js"
      )
    ),
    tags$script(HTML(DP_JS))
  ),
  cicerone::use_cicerone(),
  div(
    class = "app-shell",
    rail_nav,
    div(
      class = "main",
      div(
        class = "page-section",
        `data-page` = "Workbench",
        style = "display:block;",
        workbench_page
      ),
      div(
        class = "page-section",
        `data-page` = "About",
        style = "display:none;",
        about_page
      ),
      div(
        class = "footer",
        "Drug Perturbation Explorer · MIT © 2026 Posit Software, PBC · Authored by Samuel Bharti"
      )
    )
  ),
  # Page-level overlays: scrim + the assistant, query, and upload drawers.
  div(id = "scrim", class = "scrim", onclick = "DP.closeAll()"),
  div(
    class = "drawer",
    id = "assistant_drawer",
    byok_chat_ui_plain(
      "chat",
      title = "Drug Perturbation assistant",
      subtitle = "Bring your own Gemini / OpenAI / Anthropic key.",
      placeholder = "Ask about the panel, query, or a hit...",
      starters = c(
        "Summarise this reference panel and query signature.",
        "Which drugs most strongly mimic the query?",
        "Which drugs reverse the signature (repurposing candidates)?",
        "Break the top hit down by cell line.",
        "Switch to the LINCS L1000 panel.",
        "Lower the mimic / reverser threshold to 0.1."
      )
    )
  ),
  query_drawer,
  upload_drawer
)

server <- function(input, output, session) {
  # --- Guided demo tour (the "Demo" item in the rail) ---------------------
  demo_guide <- cicerone::Cicerone$new(overlay_click_next = TRUE)$step(
    "controls_panel",
    "1. Set up the analysis",
    paste(
      "Start here in the console: pick a reference panel, choose the",
      "connectivity score, and set the mimic / reverser threshold. These are",
      "global and drive every view."
    )
  )$step(
    "stat_ribbon",
    "At a glance",
    "Perturbation and mechanism counts for the loaded panel, plus how many drugs mimic or reverse your query at the current threshold."
  )$step(
    "dataset_card",
    "About this panel",
    "A quick summary of the loaded panel: design, perturbation and gene counts, cell lines, source, and a link to the data portal."
  )$step(
    "hdr-query",
    "Query signature",
    "The up / down genes you are matching perturbations against, prefilled from a real DE contrast. Click Edit signature to change them in a slide-in editor; everything re-scores against it."
  )$step(
    "hdr-connectivity",
    "Connectivity leaderboard",
    "Every reference perturbation ranked by connectivity. Positive scores mimic the query, negative scores reverse it. Select a row to inspect that hit in Compound detail."
  )$step(
    "hdr-distribution",
    "Score distribution",
    "How connectivity scores spread across the panel. Dashed lines mark your threshold; the highlight marks the selected hit's score."
  )$step(
    "hdr-detail",
    "Compound detail",
    "The selected hit's mechanism of action (MOA) across the panel, broken down by cell line or dose."
  )$step(
    "hdr-heatmap",
    "Top-hits heatmap",
    "Query genes across the strongest mimics and reversers, row z-scored so each perturbation's direction is comparable."
  )$step(
    "open_assistant",
    "AI assistant",
    "Open the assistant (bring your own API key) to ask about any view, or have it drive the controls for you."
  )$step(
    ".rail-nav .navlink[data-page='About']",
    "Learn more",
    "Finally, open the About page (in the left rail) for full data provenance, methods, and citations. That's the tour!",
    is_id = FALSE
  )
  observeEvent(input$demo, demo_guide$init()$start())

  # --- Stat ribbon: at-a-glance counts for the current panel + query --------
  output$stat_ribbon <- renderUI({
    meta <- dataset()$pert_meta
    thr <- input$thr %||% 0.3
    sc <- tryCatch(scores()$score, error = function(e) NULL)
    n_mimic <- if (is.null(sc)) NA_integer_ else sum(sc >= thr, na.rm = TRUE)
    n_rev <- if (is.null(sc)) NA_integer_ else sum(sc <= -thr, na.rm = TRUE)
    stat <- function(cls, k, v) {
      div(class = paste("stat", cls), div(class = "k", k), div(class = "v", v))
    }
    div(
      class = "stat-ribbon",
      stat("", "Perturbations", nrow(meta)),
      stat("", "Mechanisms", length(unique(meta$moa))),
      stat("mimic", "Mimics", if (is.na(n_mimic)) "-" else n_mimic),
      stat("reverse", "Reversers", if (is.na(n_rev)) "-" else n_rev)
    )
  })

  # One shared reference panel: a bundled contract dir, or the user's uploaded
  # CSVs (validated through the same contract).
  uploaded <- data_upload_validate_server(
    "dp_upload",
    reader = read_perturbation_dataset,
    files = drug_upload_files
  )
  dataset <- reactive({
    if (identical(input$dataset, "__upload__")) {
      req(uploaded())
      uploaded()
    } else {
      read_perturbation_dataset(file.path("data", input$dataset))
    }
  })
  profiles <- reactive(perturbation_profile_matrix(dataset()))

  # Bring-your-own-data drawer wiring. Selecting "Upload your own…" opens the
  # drawer; any bundled panel is remembered so a cancelled upload can fall back
  # to it rather than leaving the app on an empty "__upload__" selection.
  prev_dataset <- reactiveVal(unname(datasets[[1]]))
  observeEvent(input$dataset, {
    if (identical(input$dataset, "__upload__")) {
      session$sendCustomMessage("open_dp_upload", TRUE)
    } else {
      prev_dataset(input$dataset)
    }
  })
  observeEvent(input$dp_upload_closed, {
    if (identical(input$dataset, "__upload__") && is.null(uploaded())) {
      updateSelectInput(session, "dataset", selected = prev_dataset())
    }
  })

  # Example query prefill from the bundled panel; empty for uploads.
  query <- reactive({
    if (identical(input$dataset, "__upload__")) {
      return(data.frame(gene = character(), direction = character()))
    }
    utils::read.csv(
      file.path("data", input$dataset, "query_example.csv"),
      stringsAsFactors = FALSE
    )
  })

  # Genes the assistant pushed into the query (via set_query_signature); NULL
  # means "follow the panel's example query". Reset on a panel switch.
  agent_query <- reactiveVal(NULL)
  observeEvent(input$dataset, agent_query(NULL))

  # Query builder (in the query drawer): gene-selectors seeded from the
  # assistant's pushed query if any, else the panel's example query.
  up_sel <- gene_selector_server(
    "qup",
    choices = reactive(rownames(profiles())),
    selected = reactive({
      ag <- agent_query()
      if (!is.null(ag)) ag$up else query()$gene[query()$direction == "up"]
    })
  )
  down_sel <- gene_selector_server(
    "qdown",
    choices = reactive(rownames(profiles())),
    selected = reactive({
      ag <- agent_query()
      if (!is.null(ag)) ag$down else query()$gene[query()$direction == "down"]
    })
  )

  # Compact query summary shown in the console.
  output$query_summary <- renderUI({
    up <- length(intersect(up_sel(), rownames(profiles())))
    down <- length(intersect(down_sel(), rownames(profiles())))
    tags$span(
      class = "qchip",
      tags$span(class = "up", HTML("&#9650;"), paste0(" ", up, " up")),
      tags$span(class = "sep", "·"),
      tags$span(class = "down", HTML("&#9660;"), paste0(" ", down, " down"))
    )
  })

  scores <- reactive({
    up <- intersect(up_sel(), rownames(profiles()))
    down <- intersect(down_sel(), rownames(profiles()))
    shiny::validate(shiny::need(
      length(up) + length(down) > 0,
      "Select query genes present in this reference panel."
    ))
    connectivity_score(profiles(), up, down, method = input$method)
  })

  # --- Reference panel card: design, size, source, reference, links -------
  output$dataset_card <- renderUI({
    ds <- dataset()
    meta <- ds$pert_meta
    n_pert <- nrow(meta)
    n_gene <- nrow(ds$profiles)
    cells <- sort(unique(meta$cell_line))
    n_moa <- length(unique(meta$moa))
    info <- dataset_info[[input$dataset]]
    if (is.null(info)) {
      info <- list(
        title = "Your uploaded panel",
        design = NULL,
        source = "User-provided CSVs (matching the perturbation data contract)",
        portal = NULL,
        portal_label = NULL,
        reference = NULL,
        doi = NULL,
        license = NULL
      )
    }
    line <- function(k, v) {
      if (is.null(v)) {
        NULL
      } else {
        div(class = "ds-line", div(class = "ds-k", k), div(class = "ds-v", v))
      }
    }
    ref <- if (!is.null(info$reference)) {
      div(
        class = "ds-line",
        div(class = "ds-k", "Reference"),
        div(
          class = "ds-v",
          info$reference,
          if (!is.null(info$doi)) {
            tagList(
              " ",
              tags$a(
                href = info$doi,
                target = "_blank",
                rel = "noopener",
                "DOI"
              )
            )
          }
        )
      )
    }
    div(
      class = "panel",
      div(
        class = "panel-head",
        div(class = "eyebrow", "Reference panel"),
        h3(class = "panel-title", info$title)
      ),
      div(
        class = "panel-body",
        div(
          class = "ds-grid",
          div(
            line("Design", info$design),
            div(
              class = "ds-line",
              div(class = "ds-k", "Panel"),
              div(
                class = "ds-v",
                sprintf(
                  "%d perturbations · %d genes · %d MOAs",
                  n_pert,
                  n_gene,
                  n_moa
                )
              )
            ),
            line("Cell lines", paste(cells, collapse = ", "))
          ),
          div(line("Source", info$source), ref, line("License", info$license))
        ),
        div(
          class = "ds-actions",
          if (!is.null(info$portal)) {
            tags$a(
              href = info$portal,
              target = "_blank",
              rel = "noopener",
              class = "btn-line",
              icon("up-right-from-square"),
              paste0(" ", info$portal_label %||% "Data portal")
            )
          },
          tags$a(
            class = "ds-more",
            style = "color:var(--teal-deep);",
            onclick = "DP.nav('About')",
            "Read more on the About page →"
          )
        )
      )
    )
  })

  # --- Connectivity table (row selection marks a hit) ----------------------
  ct <- connectivity_table_server(
    "ct",
    scores = scores,
    pert_meta = reactive(dataset()$pert_meta),
    mimic_threshold = reactive(input$thr)
  )

  # --- Score distribution (highlights the selected hit's score) ------------
  selected_score <- reactive({
    sel <- ct$selected()
    if (length(sel) == 0) {
      return(NULL)
    }
    sc <- scores()
    sc$score[match(sel[1], sc$pert_id)]
  })
  score_distribution_server(
    "dist",
    scores = scores,
    mimic_threshold = reactive(input$thr),
    highlight = selected_score
  )

  # --- Top-hits heatmap: query genes x top mimic/reverser perturbations -----
  top_perts <- reactive({
    sc <- scores()
    ids <- c(utils::head(sc$pert_id, n_side), utils::tail(sc$pert_id, n_side))
    score_by_id <- sc$score[match(ids, sc$pert_id)]
    data.frame(
      sample = ids,
      group = ifelse(score_by_id > 0, "Mimic", "Reverser"),
      stringsAsFactors = FALSE
    )
  })
  heatmap_server(
    "hits",
    matrix = profiles,
    rows = reactive(c(up_sel(), down_sel())),
    metadata = top_perts,
    scale = reactive("row"),
    cluster_rows = reactive(TRUE),
    group_col = reactive("group"),
    # The full query signature is ~150 genes: too many to label legibly, so
    # hide the row labels - the colour field still reads as a landscape.
    show_features = reactive(FALSE)
  )

  # --- Compound detail: the selected hit + its mechanism (MOA) -------------
  detail_pert <- reactive({
    sel <- ct$selected()
    if (length(sel) > 0) sel[1] else scores()$pert_id[1]
  })
  detail_moa <- reactive({
    m <- dataset()$pert_meta
    m$moa[match(detail_pert(), m$pert_id)]
  })
  output$detail_header <- renderUI({
    pid <- detail_pert()
    m <- dataset()$pert_meta
    i <- match(pid, m$pert_id)
    sc <- scores()
    s <- sc$score[match(pid, sc$pert_id)]
    thr <- input$thr %||% 0.3
    dir <- if (is.na(s)) {
      "neutral"
    } else if (s >= thr) {
      "mimic"
    } else if (s <= -thr) {
      "reverse"
    } else {
      "neutral"
    }
    dirlab <- c(mimic = "Mimic", reverse = "Reverser", neutral = "Neutral")[[
      dir
    ]]
    div(
      class = "detail-head",
      tags$span(class = "drug", m$drug[i]),
      tags$span(class = paste("dchip", dir), dirlab),
      tags$span(class = "moa", m$moa[i] %||% "unknown MOA"),
      tags$span(
        class = "score",
        if (is.na(s)) "" else sprintf("score %.3f", s)
      )
    )
  })
  output$detail_label <- renderText({
    sprintf(
      "Connectivity by %s across the %s MOA",
      sub("_", " ", input$detail_by),
      detail_moa()
    )
  })
  group_comparison_server(
    "detail",
    values = reactive({
      m <- dataset()$pert_meta
      ids <- m$pert_id[m$moa == detail_moa()]
      sc <- scores()
      stats::setNames(sc$score[match(ids, sc$pert_id)], ids)
    }),
    metadata = reactive(data.frame(
      sample = dataset()$pert_meta$pert_id,
      cell_line = dataset()$pert_meta$cell_line,
      dose = factor(dataset()$pert_meta$dose),
      stringsAsFactors = FALSE
    )),
    value_label = reactive("connectivity score"),
    group_col = reactive(input$detail_by)
  )

  # --- Assistant: scoped, tool-using BYOK chat ----------------------------
  # A plain (non-reactive) mirror of the app's current state, kept current by an
  # observer below, so the assistant's tools read live state safely mid-stream.
  chat_state <- new.env(parent = emptyenv())

  fmt_hit <- function(tbl, i) {
    sprintf(
      "%s [%s] %s: %.3f",
      tbl$drug[i],
      tbl$pert_id[i],
      tbl$moa[i],
      tbl$score[i]
    )
  }

  dp_system_prompt <- paste(
    "You are the Drug Perturbation Explorer assistant, embedded in a CMap /",
    "LINCS-style connectivity app. The user builds an up/down query signature",
    "and scores one loaded reference panel of perturbations (WTCS or cosine) to",
    "find drugs that MIMIC (positive score) or REVERSE (negative score) the",
    "signature -- the basis for drug-repurposing hits. Your ONLY job is to help",
    "the user explore and interpret THIS app: its current panel, query, and",
    "views -- the ranked connectivity table, the score distribution, the",
    "top-hits heatmap, and the compound-detail MOA breakdown.",
    "",
    "Before answering about a view, call the matching read tool for its live",
    "state: panel_info, describe_query, connectivity_hits,",
    "describe_distribution, describe_drug_detail. Never invent drug names, MOAs,",
    "counts, or scores -- quote the tool output. Note real LINCS scores are",
    "modest. Explain connectivity scores, mimic vs reverser, and MOA plainly.",
    "",
    "You can also DRIVE the app's controls when the user asks -- then briefly say",
    "what you changed:",
    "- set_dataset: switch the loaded reference panel.",
    "- set_method: switch the connectivity score (weighted WTCS or cosine).",
    "- set_threshold: change the mimic / reverser |score| cutoff.",
    "- set_query_signature: replace the up / down query genes.",
    "- set_focus_drug: select a hit in the table (drives Compound detail).",
    "- set_detail_breakdown: break Compound detail down by cell line or dose.",
    "After changing a control, you may re-read the relevant view to interpret it.",
    "",
    "Refuse anything outside Drug Perturbation Explorer and this panel: for",
    "off-topic or general questions, briefly decline and point back to what the",
    "app can do. Be concise.",
    sep = "\n"
  )

  dp_tools <- list()
  if (requireNamespace("ellmer", quietly = TRUE)) {
    dp_tools <- list(
      ellmer::tool(
        function() {
          meta <- chat_state$dataset$pert_meta
          cells <- sort(unique(meta$cell_line))
          paste(
            c(
              paste0("Reference panel: ", chat_state$dataset_label, "."),
              paste0(
                "Perturbations: ",
                nrow(meta),
                "; genes profiled: ",
                nrow(chat_state$dataset$profiles),
                "; distinct MOAs: ",
                length(unique(meta$moa)),
                "."
              ),
              paste0("Cell lines: ", paste(cells, collapse = ", "), "."),
              paste0(
                "Connectivity score: ",
                if (identical(chat_state$method, "wtcs")) {
                  "weighted (WTCS)"
                } else {
                  "cosine"
                },
                "; mimic/reverser threshold: |score| >= ",
                chat_state$threshold,
                "."
              )
            ),
            collapse = "\n"
          )
        },
        name = "panel_info",
        description = paste(
          "Meta on the currently loaded reference panel: perturbation and gene",
          "counts, cell lines, distinct MOAs, and the active score/threshold."
        )
      ),
      ellmer::tool(
        function() {
          up <- chat_state$up
          down <- chat_state$down
          paste(
            c(
              paste0(
                "Query signature: ",
                length(up),
                " up gene(s), ",
                length(down),
                " down gene(s)."
              ),
              paste0("Up: ", paste(utils::head(up, 40), collapse = ", "), "."),
              paste0(
                "Down: ",
                paste(utils::head(down, 40), collapse = ", "),
                "."
              )
            ),
            collapse = "\n"
          )
        },
        name = "describe_query",
        description = paste(
          "The current up / down query gene sets being scored against the panel."
        )
      ),
      ellmer::tool(
        function() {
          tbl <- chat_state$table
          counts <- connectivity_direction_counts(tbl)
          n <- nrow(tbl)
          top_m <- utils::head(seq_len(n), 5)
          top_r <- rev(utils::tail(seq_len(n), 5))
          paste(
            c(
              paste0(
                "At |score| >= ",
                chat_state$threshold,
                ": ",
                counts[["Mimic"]],
                " mimic(s), ",
                counts[["Reverser"]],
                " reverser(s), ",
                counts[["Neutral"]],
                " neutral."
              ),
              "Top mimics (drug [pert_id] MOA: score):",
              paste0("  ", vapply(top_m, function(i) fmt_hit(tbl, i), "")),
              "Top reversers:",
              paste0("  ", vapply(top_r, function(i) fmt_hit(tbl, i), ""))
            ),
            collapse = "\n"
          )
        },
        name = "connectivity_hits",
        description = paste(
          "Ranked connectivity summary: mimic/reverser/neutral counts at the",
          "current threshold, plus the strongest mimics and reversers."
        )
      ),
      ellmer::tool(
        function() {
          sc <- chat_state$scores$score
          t <- chat_state$threshold
          paste(
            c(
              paste0("Scores across ", length(sc), " perturbations."),
              paste0(
                "Range ",
                sprintf("%.3f", min(sc)),
                " to ",
                sprintf("%.3f", max(sc)),
                "; median ",
                sprintf("%.3f", stats::median(sc)),
                "."
              ),
              paste0(
                sum(sc >= t),
                " score at/above +",
                t,
                " (mimics); ",
                sum(sc <= -t),
                " at/below -",
                t,
                " (reversers)."
              )
            ),
            collapse = "\n"
          )
        },
        name = "describe_distribution",
        description = paste(
          "Score-distribution summary: range, median, and how many",
          "perturbations fall in the mimic / reverser tails at the threshold."
        )
      ),
      ellmer::tool(
        function() {
          tbl <- chat_state$table
          pid <- chat_state$selected_pert
          if (is.null(pid) || length(pid) == 0) {
            pid <- tbl$pert_id[1]
          }
          i <- match(pid, tbl$pert_id)
          moa <- tbl$moa[i]
          same <- tbl[tbl$moa == moa & !is.na(tbl$moa), , drop = FALSE]
          by <- chat_state$detail_by
          levels <- split(same$score, same[[by]])
          lvl_txt <- vapply(
            names(levels),
            function(k) {
              sprintf(
                "%s: mean %.3f (n=%d)",
                k,
                mean(levels[[k]]),
                length(levels[[k]])
              )
            },
            ""
          )
          paste(
            c(
              paste0(
                "Focused hit: ",
                tbl$drug[i],
                " [",
                pid,
                "], MOA '",
                moa,
                "', score ",
                sprintf("%.3f", tbl$score[i]),
                "."
              ),
              paste0(
                nrow(same),
                " perturbation(s) share this MOA. Mean score by ",
                sub("_", " ", by),
                ":"
              ),
              paste0("  ", lvl_txt)
            ),
            collapse = "\n"
          )
        },
        name = "describe_drug_detail",
        description = paste(
          "Compound-detail summary: the selected (or top) hit, its MOA and score,",
          "and the mean connectivity of same-MOA perturbations by the current",
          "breakdown (cell line or dose)."
        )
      ),
      # --- Control tools ----------------------------------------------------
      ellmer::tool(
        function(dataset) {
          choices <- setdiff(unname(datasets), "__upload__")
          if (!dataset %in% choices) {
            return(paste0("Unknown panel. Choose one of: ", toString(choices)))
          }
          updateSelectInput(session, "dataset", selected = dataset)
          paste0("Reference panel switched to ", dataset, ".")
        },
        name = "set_dataset",
        description = paste(
          "Switch the loaded reference panel. perturbation-synthetic =",
          "BRCA-grounded synthetic demo; perturbation-lincs = real LINCS L1000",
          "MCF7 panel."
        ),
        arguments = list(
          dataset = ellmer::type_enum(
            setdiff(unname(datasets), "__upload__"),
            description = "The panel id to load"
          )
        )
      ),
      ellmer::tool(
        function(method) {
          updateRadioButtons(session, "method", selected = method)
          paste0(
            "Connectivity score set to ",
            if (identical(method, "wtcs")) "weighted (WTCS)" else "cosine",
            "."
          )
        },
        name = "set_method",
        description = paste(
          "Set the connectivity score: 'wtcs' (weighted, GSEA-style) or 'cosine'",
          "(cosine similarity to the query vector)."
        ),
        arguments = list(
          method = ellmer::type_enum(
            c("wtcs", "cosine"),
            description = "The connectivity scoring method."
          )
        )
      ),
      ellmer::tool(
        function(threshold) {
          threshold <- max(0, min(1, threshold))
          updateSliderInput(session, "thr", value = threshold)
          paste0(
            "Mimic / reverser threshold set to |score| >= ",
            threshold,
            "."
          )
        },
        name = "set_threshold",
        description = paste(
          "Set the mimic / reverser |score| cutoff (0 to 1). Above +t is a mimic,",
          "below -t a reverser. Real LINCS scores are modest -- try 0.1-0.2."
        ),
        arguments = list(
          threshold = ellmer::type_number(
            "The |score| cutoff, 0 to 1."
          )
        )
      ),
      ellmer::tool(
        function(up_genes = NULL, down_genes = NULL) {
          genes <- rownames(chat_state$profiles)
          up <- intersect(up_genes %||% character(0), genes)
          down <- intersect(down_genes %||% character(0), genes)
          if (length(up) + length(down) == 0) {
            return(paste(
              "None of those genes are in the current panel; query unchanged.",
              "Query genes must match the panel's gene space."
            ))
          }
          agent_query(list(up = up, down = down))
          paste0(
            "Query updated: ",
            length(up),
            " up gene(s) and ",
            length(down),
            " down gene(s) applied."
          )
        },
        name = "set_query_signature",
        description = paste(
          "Replace the up / down query gene sets (must be gene symbols in the",
          "current panel). Everything re-scores against the new query. Omit a",
          "side to leave it empty."
        ),
        arguments = list(
          up_genes = ellmer::type_array(
            items = ellmer::type_string("A gene symbol"),
            description = "Up-regulated query genes",
            required = FALSE
          ),
          down_genes = ellmer::type_array(
            items = ellmer::type_string("A gene symbol"),
            description = "Down-regulated query genes",
            required = FALSE
          )
        )
      ),
      ellmer::tool(
        function(perturbation) {
          tbl <- chat_state$table
          i <- which(
            tbl$pert_id == perturbation | tbl$drug == perturbation
          )
          if (length(i) == 0) {
            return(paste0(
              "No hit matches '",
              perturbation,
              "'. Give a pert_id or drug name from the connectivity table."
            ))
          }
          DT::selectRows(DT::dataTableProxy("ct-tbl"), i[1])
          paste0(
            "Selected ",
            tbl$drug[i[1]],
            " [",
            tbl$pert_id[i[1]],
            "]; Compound detail now focuses it."
          )
        },
        name = "set_focus_drug",
        description = paste(
          "Select a hit in the connectivity table (by pert_id or drug name),",
          "which drives the Compound detail view and the score-distribution",
          "highlight."
        ),
        arguments = list(
          perturbation = ellmer::type_string(
            "A pert_id or drug name from the connectivity table."
          )
        )
      ),
      ellmer::tool(
        function(by) {
          updateRadioButtons(session, "detail_by", selected = by)
          paste0(
            "Compound detail now breaks down by ",
            if (identical(by, "cell_line")) "cell line" else "dose",
            "."
          )
        },
        name = "set_detail_breakdown",
        description = paste(
          "Set how Compound detail groups the selected hit's MOA: by 'cell_line'",
          "or 'dose'."
        ),
        arguments = list(
          by = ellmer::type_enum(
            c("cell_line", "dose"),
            description = "The Compound-detail breakdown dimension."
          )
        )
      )
    )
  }

  byok_chat_server(
    "chat",
    system_prompt = dp_system_prompt,
    tools = dp_tools
  )

  # --- Keep the assistant's state mirror current --------------------------
  observe({
    chat_state$dataset <- dataset()
    chat_state$dataset_label <- names(datasets)[match(input$dataset, datasets)]
    chat_state$profiles <- profiles()
    chat_state$method <- input$method
    chat_state$threshold <- input$thr
    chat_state$up <- intersect(up_sel(), rownames(profiles()))
    chat_state$down <- intersect(down_sel(), rownames(profiles()))
    chat_state$scores <- scores()
    chat_state$table <- ct$data()
    chat_state$selected_pert <- ct$selected()
    chat_state$detail_by <- input$detail_by
  })
}

shinyApp(ui, server)
